org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServersRegistry.java

- Make `LanguageServersRegistry#getInstance` thread-safe
- Rename `LanguageServerDefinition`'s field `langugeIdMappings` to `languageIdMappings`

Improve LanguageServersRegistry

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/EditorToOutlineAdapterFactory.java

- put the ID of the outline view into a static field
- change private static final variable name `lsCache` to `LANG_SERVER_CACHE`
- avoid repeated `(IEditorPart) adaptableObject` casting

Minor code improvements in EditorToOutlineAdapterFactory

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileDialog.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java

This PR fixes the issue that when opening the quick outline the nearest outline item is automatically selected in the text editor, i.e. the selection in the text editor is changed merely by opening the quick outline.
*Example:*
The editor cursor is in line 54. I press CTRL+O to open the quick outline and the `bindEvents` method name is selected automatically.
With this PR the nearest item is still selected in the outline tree but the text editor selection is not changed only by opening the outline.

Don't move cursor/change text selection when opening quick outline

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

Instead of that, use only the file name to extract the content types.

Do not raise exception if the file does not exists

---

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF
org.eclipse.lsp4e.test/pom.xml
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

Fixes #29.
Signed-off-by: Pierre-Yves Bigourdan <10694593+PyvesB@users.noreply.github.com>

Ensure workspaceFolders uses standard file:// prefix

---

documentation/using-built-in-debug-adapter-launch-configuration.md

Application Under Debug
relates to #49

Fix documentation to use existing parameters to attach to the

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSIncompleteCompletionProposal.java

when only 1 position is given so we can simply just place caret.

Issue #58 - Avoid LinkedMode edition for completion

---

org.eclipse.lsp4e/plugin.properties
org.eclipse.lsp4e/plugin.xml

Change-Id: If2aa18072e2154aad5dfa10c0cd363cf081d47d6

Every Outline view now has an extra "Sort Outline" toggle #35

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

implementation of AbstractTextEditor

Issue #63 - getDocument(ITextEditor) incorrectly assumes an

---

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/breakpoints/TextSelectionToIVariable.java

[Debug] Abort adapter if variable cannot be found

---

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/breakpoints/TextSelectionToIVariable.java

* Prefer showing available variables over evaluation results (less CPU
consumed, consistency with Variables view, editable values)
* Only assume that variables start with a letter, to avoid evaluating
constants (eg integer values).

Improve TextSelectionToIVariable adapter

---

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/breakpoints/DocumentUtils.java
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/breakpoints/TextSelectionToIVariable.java

Ignore documents that are not related to a current DSPStackFrame.

[Debug] Adapters only participate to variable resolution on related docs

---

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java

Issue: #128
Change-Id: I2ae7058d4dca56d41e854a8b6007419b6ae06962

An NPE happens when debug target cannot be initialized #128

---

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF
org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF
org.eclipse.lsp4e/META-INF/MANIFEST.MF
org.eclipse.lsp4e/pom.xml
target-platforms/target-platform-latest/target-platform-latest.target

Update to LSP4J 0.14.0
Fixes #135

Update to LSP4J 0.14.0

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/diagnostics/DiagnosticsTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java

When a language server mounts a project, it can send back diagnostics for the whole project, not merely those files that have been opened in the IDE so far. In order to be able to create the annotations, LSPDiagnosticsToMarkers will mount the file buffers temporarily. At present, it is not releasing them afterwards. This has caused us some issues with large projects with a great many files and markers.
See the note on reference counting at https://help.eclipse.org/2020-09/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcore%2Ffilebuffers%2FIFileBufferManager.html

Fix buffer leak in diagnostics handler

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/AllCleanRule.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/TestUtils.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/color/ColorTest.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/diagnostics/DiagnosticsTest.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/OutlineContentTest.java

Content Test
Turns out content *does* matter, a bit!

testing: Clean up unnecessary BadLocationExceptions thrown from Outline

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/linkedediting/LinkedEditingTest.java

I think there were always potentially multiple annotations at the
expected location, and depending on luck would get the one we were
expecting first.

testing: Mitigate flaky LinkedEdit test

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

by completing the initialiation future before stopping the server.

Improve diagnostics of LS startup failures

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java

by reducing the amount of calls to marker.getAttribute.
In addition, to improve code clarity, a method getLanguageServerFutures
has been factored out.

Improve performance of LSPCodeActionMarkerResolution

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

Announce LS client rename capability `PrepareSupport`

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

This implements the third option *"Move the call to StreamConnectionProvider.getInitializationOptions(rootURI) method before the call to StreamConnectionProvider.start()"* described in #157

Call lspStreamProvider.getInitializationOptions(rootURI) before .start()

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LoggingStreamConnectionProviderProxy.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/server/StreamConnectionProvider.java

...in case LanguageServerWrapper initialProject and initialPath are null or
point non-existing location

LanguageServerWrapper: Don't set rootURI if initialProject and initialPath are null or invalid

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java

WorkDoneProgressNotification that arrive before the job has been
started are kept in an orphan, which are checked by the jobs so that 
we do not have orphan jobs which run forever.

Keep track of out of order notifications in the LSP Progress Manager

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

Hi all,
This PR adds support to navigate to a document when receiving the `window/showDocument` message.
Best,
Bastian

feat: add support for `window/showDocument`

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java

also add an exceptionally call to avoid errors being lost

Prevent NPE when Matches with null resources are added as match

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java

and only check for resolutions if there is no remediation.

Check current calculated remediation in hasResolutions

---

org.eclipse.lsp4e/plugin.xml
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/LSPCodeMining.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/InlayHintProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/LSPLineContentCodeMining.java

Support for textDocument/inlayHint
Fixes #125

Support for textDocument/inlayHint

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/CompleteCompletionTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java

https://github.com/eclipse/lsp4e/issues/230

Support AdjustIndentation

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/InlayHintProvider.java

The new inlay hints implementation is really cool, but our language server respects the viewport range in the request so as things stand doesn't return any data.
The protocol is designed (a la Vscode) to support optimising traffic for large files by only requesting hints for the visible portion of the document, i.e. the viewport. I don't think Eclipse can support this - I stuck some breakpoints/logging in and only got requests for the code mining when the document was loaded or changed, not when I scrolled an unmodified document. If that's correct, then the best and only thing we can do is to send the full document range.
What do people think? @angelozerr @mickaelistria 
Cf https://github.com/eclipse/lsp4e/pull/227#discussion_r956560920 and …

Use full document range for inlay hints request

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/color/ColorInformationMining.java

Apply update of color in the Display Thread

Apply update of color in the Display Thread

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServersRegistry.java

create DiagnosticsConsumer for launch config based server definitions
Fixes #239

create DiagnosticsConsumer for launch config based server definitions

---

org.eclipse.lsp4e/pom.xml

Update Highlight.js to 11.6.0

---

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java

The full details about the why for this PR are in https://github.com/eclipse/lsp4e/issues/262#issuecomment-1286408503
- Reverts #66
- Fixes #262
- Fixes #51

Allow initialized processing and launch to run in parallel

---

target-platforms/target-platform-latest/target-platform-latest.target

The 3.0.42 is no longer available

fix mylyn URI

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java

Hopefully understood what potential NPEs needed fixing.

Fix potential NPEs

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSFindReferences.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java

"Find References" sometimes doesn't work in TypeScript files
Fixes #297

"Find References" sometimes doesn't work in TypeScript files

---

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPBreakpointManager.java

Fixes https://github.com/eclipse/lsp4e/issues/301

Don't add initially disabled breakpoints

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java

Draft implementation of "alwaysUp" attribute for language server extension point.

Support "Always Up" language servers

---

org.eclipse.lsp4e.debug/plugin.xml
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPValue.java
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/presentation/DAPWatchExpression.java

Fixes https://github.com/eclipse/lsp4e/issues/306

Support Watch Expressions with DAP

---

org.eclipse.lsp4e/build.properties
target-platforms/target-platform-latest/target-platform-latest.target

Use GSON and xbase from same source as LSP4J

Fix target-platform

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

Update CompletionItemResolveSupportCapabilities correctly

Update CompletionItemResolveSupportCapabilities correctly

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CommandMarkerResolution.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java

In the steps of `LSPDiagnosticsToMarkers#updateMarkers(...)` same done in other places

Disconnect text buffers if necessary

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

fix: do not try to parse empty or null fragment 

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionCompletionProposal.java

Support left of CodeActionProvider

Support left of CodeActionProvider

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerPlugin.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java

Extracted from 1be007dfc5460fdb898fd48fbfb65139b2aaa0c9

New  api: port core document changes over

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/LSPTextHover.java

Getting rid of infinite waiting in LSPTextHover
Issue: #175

UIFrezze at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverRegion(LSPTextHover.java:150) #175

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java

Getting rid of infinite waiting in SemanticHighlightReconcilerStrategy

Fix possible freeze in SemanticHighlightReconcilerStrategy

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/color/DocumentColorProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/OpenDeclarationHyperlinkDetector.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameHandler.java

This PR reduces repetitive code to increase maintainability and comprehensibility

simplify LSPEclipseUtils.hasCapability and use where applicable

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServersRegistry.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/OpenDeclarationHyperlinkDetector.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticTokensDataStreamProcessor.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileDialog.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileHandler.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceDialog.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/refactoring/LSPTextChange.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/server/ProcessOverSocketStreamConnectionProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/server/ProcessStreamConnectionProvider.java

This PR fixes a few issues my IDE is nagging me about.

Minor code cleanup

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java

This PR reduces the visibility of implementation internal utility functions.

Reduce visibility of internal functions in LanguageServiceAccessor

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java

Extract API to get list of started language server wrappers and reuse it inside LanguageServiceAccessor

Extract API to get list of started language server wrappers

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/color/ColorInformationMining.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/color/DocumentColorProvider.java

Originally submitted as example code in #333 , now reimplemented on top of #344

New api: Port color minings

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/OpenDeclarationHyperlinkDetector.java

Port to new API of demo code originally done in #251 
@angelozerr FYI: I'm not trying to subvert your work in #238 ...! I've been thinking about how best to implement cancel support in the new API, and in particular how to make it as general as possible. I think I know roughly how to do it so I will try and get the general design in place and then see how it works in this specific instance. Doing the API port separately should hopefully make the discussion a bit easier so we can see exactly how cancel support interacts with everything else.

New API: Port hyperlink detection

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java

Fix NPE if a location is null that happens during execution of the LSP4E tests

Fix NPE if a location is null that happens during execution of the tests

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java

@ahmedneilhussain , does it makes sense?

New API: port FoldingReconcilingStrategy

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingBase.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingReconcilingStrategy.java

@ahmedneilhussain , ok for you?

New API: Port link edit

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java

`anyMatching` will connect the document if not already connected, while
`LanguageServiceAccessor.getLanguageServers(..., capabilities -> ...)
would not do that.
So if the document is not connected, this call will take longer and will
have a side effect.
I think anyMatching should not connect documents, they should be
connected on demand when any of the collect/compute methods are called.

Do not connect documents in anyMatching

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java

"newName" will be used as placeholder. Adding a fatal error is not necessary.

If prepare rename timeouts, the rename operation can still be done,

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java

If the default timeout is not met, we return that a server is matching. Usually the pattern is to ask anyMatching before enabling a functionality on a given document, but if the functionality is enabled and there will always be follow-up request to use the functionality.
Usually the call is done to show/hide some menu item on the UI. It is better to return quick and let the action do nothing if the user actually runs the action than to block for a (potentially) long time the creation on the menu items.

Implement anyMatching as a non blocking call using a default timeout

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/references/FindReferencesTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSFindReferences.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java

@ahmedneilhussain : what about this one?

New API: Port find references

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/CancellationUtil.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java

Do not handle cancellation exceptions in LanguageServers, as each
consumers might want to react different to a cancellation

Do not handle cancellation exceptions in LanguageServers

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java

Deprecate methods in LanguageServerAccessor allowing access to a LanguageServer

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/RunningLanguageServerTest.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/WorkspaceFoldersTest.java

Remove usages of getInitializedLanguageServers outside of

---

org.eclipse.lsp4e/plugin.properties
org.eclipse.lsp4e/plugin.xml
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyCommandHandler.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyContentProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyLabelProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyView.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyViewInput.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyViewTreeNode.java

Basic call hierarchy view added that uses the LSP prepareCallHierarchy and callHierarchyIncomingCalls APIs to provide content.

Basic call hierarchy view support added.

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyCommandHandler.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyContentProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyLabelProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyView.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyViewInput.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyViewTreeNode.java

Also added some null/nonNull annotations and converted whitespaces to tabs to follow the rest of the project code.

Remove casts which are not needed in Java 17

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java

Apply code action after resolve

Apply code action after resolve

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java

thenComposeAsync on null instead of a valid CompletableFuture.

Fix NPE in LanguageServerWrapper.executeImpl when calling

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/StyleUtil.java

@mickaelistria , apparently by moving the code the execution time was shifted and we run into a thread access exception. Do you think this fix is fine?
PD: It works in the test I did.

Avoid Thread Access Exception

---

pom.xml

Required to build with Maven 3.9.0

fix(deps): bump tycho.version from 3.0.1 to 3.0.3

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java

Fix NonNull annotation and use Nullable, as the called method accepts

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/codeactions/CodeActionTests.java

Do not cleanup inside test, as the clean rule does it.

Try making tests more stable

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/codeactions/CodeActionTests.java

Prevent ArrayIndexOutOfBoundsException in tests as seen by test

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java

This PR adds a better processing during the uninstallation of SemanticHighlightReconcilerStrategy:
- Removes the repeated invokation of  `SemanticHighlightReconcilerStrategy.cancelSemanticTokensFull()` after `uninstall` is invoked (it could be invoked once again from `fullReconcile')
- Skips as much as it possible any processing after `uninstall` is invoked by disabeling it in `fullReconcile` if uninstall is already invoked (so, actually no any processing is needed after that)

Fix SemanticHighlightReconcilerStrategy uninstallation

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java

Fixes https://github.com/eclipse/lsp4e/issues/608

Fix invalid cast ProjectionViewer

---

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF

Reverting did revert the version bump.

Bump version for new stream

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

Illegal argument exception

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/SymbolsLabelProviderTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java

[#615] fix missing space in outline view text

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

Continuation of
https://github.com/redhat-developer/eclipseide-jdtls/issues/44

Reduce cases requiring a refactoring for WorksapceEdit

---

org.eclipse.lsp4e/pom.xml

Changelog: https://github.com/highlightjs/highlight.js/releases/tag/11.8.0

Update Highlight.js to 11.8.0

---

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/console/DSPProcess.java
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugElement.java
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/TransportStreams.java
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPLaunchDelegate.java
org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF

This makes the child debugging session start; however termination and some other things are not responding well.
This shouldn't be merged until LSP4J snapshots are used

Basic support for startDebugging

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java

Since content assist is triggered automatically while typing, and some servers cancel request when the content of a source changes, we check if the request has been cancelled by the server before logging an error.

Handle server cancellation

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServiceAccessorTest.java

Instead of filter().findAny().isPresent()

Use Stream.anyMatch()

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/documentLink/DocumentLinkTest.java

Add content to the file so the ranges match actual cotnent.

Fix DocumentLinkTest#testDocumentLinkExternalFile

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LoggingStreamConnectionProviderProxy.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/Messages.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/messages.properties

Add LS console name

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/CNFOutlinePage.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java

Cannot open any css file with the generic editor #752

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java

Getting rid of infinite waiting in LSContentAssistProcessor
Issue: #743

Completion "hangs" with no response #743

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/SupportedFeatures.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java

Add context to completion request

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/selectionRange/LSPSelectionRangeAbstractHandler.java

Fixes https://github.com/eclipse-m2e/m2e-core/issues/1502

Make selectionRange work on MultiPart editors

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java

support PendingUpdateAdapter in SymbolsLabelProvider

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

fix failing completion at offset 0

---

org.eclipse.lsp4e/META-INF/MANIFEST.MF
org.eclipse.lsp4e/pom.xml
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/typeHierarchy/TypeHierarchyView.java

open file from type hierarchy when file not in workspace

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/SupportedFeatures.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java
target-platforms/target-platform-latest/target-platform-latest.target

Fixes https://github.com/eclipse/lsp4e/issues/741

Declare itemDefaults capabilities

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

triggerCharacter won't be send via json rpc in case of TriggerKind.Invoked: "context":{"triggerKind":1}
fixes #794

Fix undefined triggerCharacter for TriggerKind.Invoked

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceHandler.java

see comment
https://github.com/eclipse/lsp4e/pull/801#discussion_r1324234975

Use single dispose call

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceDialog.java

The LS is supposed to deal with filtering, wildcard expansion and so on, so do not apply further filtering
Also add some cancellation support for the workspaceSymbols request

Do not filter workspace symbols in dialog

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceDialog.java

Do not perform client-side filtering in any case, do not reuse existing responses even if query pattern grows.
Fixes https://github.com/eclipse/lsp4e/issues/809

Re-ask LS for workspaceSymbols on every change

---

org.eclipse.lsp4e.test/fragment.xml
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServerWrapperTest.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/MockConnectionProviderWithStartException.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

Fix and unit test for #804: Race condition in LanguageServerWrapper

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

Will be called before reconcilers installed via for example addDocumentListener. 
For now reconcilers have to wait couple ms to make sure they will be called after didChange notification

Register documentcontentsynchronizer as prenotified listener 

---

org.eclipse.lsp4e/META-INF/MANIFEST.MF
org.eclipse.lsp4e/pom.xml
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

[#839] Add restart method

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java

`CompletionList` isIncomplete is ignored see https://github.com/eclipse/lsp4e/issues/842#issuecomment-1753364948

isIncomplete flag is ignored

---

org.eclipse.lsp4e/pom.xml

Changelog: https://github.com/highlightjs/highlight.js/releases/tag/11.9.0

Update Highlight.js to 11.9.0

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java

Such as `jar:file:/path/to/jar!/path/in/jar.java`

Improve support for URIs without path

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java

Do not retrigger LS queries (and reactions) if the context has not changed.
Fixes https://github.com/eclipse/lsp4e/issues/725

Prevent recurring pop-up

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/FocusableBrowserInformationControl.java

Error while hovering over Maven artifacts / broken #820

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/IncompleteCompletionTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java

Change-Id: I935afc7c1625d9bf151b6b2bd064ccf5000dd798

GH-896: do not adjust additional text edits when on different line

---

org.eclipse.lsp4e/plugin.xml

Remove duplicate source top-level menu

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/AbstractCompletionTest.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/IncompleteCompletionTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/Messages.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/messages.properties

Add a place-holder proposal that indicates when the list of content assist proposals is incomplete.

Indicate when content assist proposals are incomplete.

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java

[#925] Invoke folding reconcile on doc change

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

fix exception when newText.length() == 0

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/references/FindReferencesTest.java

[#930] fix flaky unit test

---

Jenkinsfile
org.eclipse.lsp4e/pom.xml
pom.xml

This PR mainly applies a few changes to the build configuration that improve build speed by reordering repo mirrors, reduces build errors because of random read timeout errors when downloading css/js resources.

Update project build configuration

---

org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServer.java

use `CompletableFuture#delayedExecutor` for delaying executions instead of blocking threads of `ForkJoinPool#commonPool` by using `Thread.sleep()` to reduce congestion of the common pool.

use delayedExecutor in MockLanguageServer for delaying

---

CONTRIBUTING.md
Jenkinsfile
README.md
org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
org.eclipse.lsp4e/plugin.xml
org.eclipse.lsp4e/schema/languageServer.exsd
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

This PR changes all references from "master" to "main". Besides the merge of this PR renaming the branch to `main` and setting it as default branch is required.

Rename head branch to main and update documentation links

---

.actrc
.github/dependabot.yml
.github/workflows/build.yml
.github/workflows/licensecheck.yml
CONTRIBUTING.md
README.md
org.eclipse.lsp4e.test/pom.xml
pom.xml

Follow-up PR for https://github.com/eclipse/lsp4e/pull/169

add github actions builds

---

org.eclipse.lsp4e/META-INF/MANIFEST.MF
org.eclipse.lsp4e/pom.xml

https://github.com/eclipse/lsp4e/issues/1019

Increase the version of org.eclipse.lsp4e to force newly signed content

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java

in the filesystem to support files which are only in the Eclipse filesystem (not in the IO filesystem)

Use the URI as the human readable name of the change instead of the path

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/diagnostics/DiagnosticsTest.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/DiagnosticAnnotation.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java

This PR addresses https://github.com/eclipse/lsp4e/issues/686

feat: add diagnostic code as suffix to marker message

---

org.eclipse.lsp4e/pom.xml

Changelog: https://github.com/highlightjs/highlight.js/releases/tag/11.10.0

Update Highlight.js to 11.10.0

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java

Remove a duplicated null check (already checked at the very beginning of the method)

refactor: remove duplicate null check

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java

the subsequent calls `currentPercentageMap.containsKey` and `currentPercentageMap.put(monitor, report.getPercentage());` in the `report(...)` method can be handled atomically using ConcurrentMap.compute to avoid potential race conditions

fix: potential race condition in LSPProgressManager#report

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java

launcherFuture.isDone() already checks if cancelled

refact: remove unnecessary launcherFuture.isCancelled() check

---

org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF
org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServer.java

to allow testing extensions of the LanguageClient.

Allow extensions of the MockLanguageServer

---

org.eclipse.lsp4e/pom.xml

Changelog: https://github.com/highlightjs/highlight.js/releases/tag/11.11.0

Update Highlight.js to 11.11.0

---

.github/workflows/build.yml
.github/workflows/licensecheck.yml
.mvn/wrapper/maven-wrapper.properties
CONTRIBUTING.md
Jenkinsfile
mvnw
mvnw.cmd

Using Maven wrapper ensures consistent builds on Jenkins, GHA and local dev environments.

build: use Maven wrapper

---

org.eclipse.lsp4e/pom.xml

Changelog: https://github.com/highlightjs/highlight.js/releases/tag/11.11.1

Update Highlight.js to 11.11.1

---

org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LSJavaProposal.java

@sebthom suggested in https://github.com/eclipse-lsp4e/lsp4e/pull/1223/files/9dc3c8f5b26c533bbae79e63c0895010c106c82f#r1999563322

Division should result in a float

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java

Support `CompletionItem` `LabelDetails` object
Separated from #1238

Label Details support

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java

fix: do not propagate the CancellationException if the feature has been

---

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/CancellationSupport.java

I've been seeing a lot of random NPEs lately with stack traces like the one below. Static analysis didn’t help pinpoint the root cause. The main issue is that the NPE only shows up late in `CancellationSupport.cancel()`, so it’s hard to tell how a null future got into the list in the first place. To catch this earlier, I added a soft null check to `CancellationSupport.execute()` that logs an NPE right when something tries to register a null future unexpectedly.
The code change also ensures that other registered futures will be cancelled as expected and processing is not stopped the moment a null future is encountered.
```py
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface.text".
!STACK 0
java.lang.NullPointerException: Cannot invoke …
```

fix: check for potential null futures in CancellationSupport.execute()

---

org.eclipse.lsp4e/META-INF/MANIFEST.MF
org.eclipse.lsp4e/schema/languageServer.exsd
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServersRegistry.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/client/DefaultLanguageClient.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/client/package-info.java

feat: move LanguageClientImpl to a package which is exported without restrictions

---

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/WorkspaceFoldersTest.java

by not relying on exact order and count of emitted events but instead wait for the expected event to be present

fix: make WorkspaceFoldersTest more predictable

---

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF
org.eclipse.lsp4e.test/pom.xml
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/OutlineContentTest.java
org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/TestUtils.java
org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF
org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockTextDocumentService.java
org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java

Correct File URI for Outline
