eclipse-lsp4e/lsp4e

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/CNFOutlinePage.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java
Use `getAdapter(ITextViewer.class)` instead of `getAdapter(ITextOperationTarget.class)` to retrieve an `ITextViewer` instance.
=> Fix adapter casting in CNFOutlinePage

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/OutlineContentTest.java, org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileDialog.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/CNFOutlinePage.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/OutlineSorter.java
- The outline and the quick outline now respect the `<commonSorter>` of the navigatorContent extension configuration.
- Additionally the quick outline doesn't use hard coded content/label providers anymore but the ones specified in the navigatorContent extension configuration.
- You will now actually see the `Computing...` message in the outline when it is initially loaded and not a blank view for 1 to 2 seconds.
=> Add support for <commonSorter> in outline

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPStackFrame.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPLaunchDelegate.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPTabGroup.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ConnectDocumentToLanguageServerSetupParticipant.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/command/CommandExecutor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/highlight/HighlightReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileDialog.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsModel.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LoggingPreferencePage.java
I ran the Eclipse Code Cleanup action with a few uncritical rules:
- Initialize collection at creation
- Make inner classes static where possible
- Primitive parsing
- Use boolean literals instead of Boolean.TRUE/FALSE when used as a primitive
- Operate on Maps directly
- Remove unused imports
- Simplify lambda expression and method reference syntax
- Use lambda where possible
- Use diamond operator
- Use Autoboxing / Unboxing
- valueOf() rather than instantiation
=> minor code cleanup

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/pom.xml
While I did set it to false by default in code at https://github.com/eclipse/lsp4e/blob/5132a7f80eabe4474ae8369dcf8d9e3448f47d95/org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/OutlineSorter.java#L67
I overlooked the declaration in the plugin.xml
=> Don't sort outline by default

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/color/DocumentColorProvider.java
Fix NPE reported in https://github.com/briandealwis/gore/issues/1:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.eclipse.lsp4j.ServerCapabilities.getColorProvider()" because "capabilities" is null
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159)
at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.ja …
```
=> fix: avoid NPE in DocumentColorProvider#isColorProvider()

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
fix #51
The parenthesis were nto placed at the right place. Only the
"initialized" future which corresponds to the server which has sent the
initialized answer has been received. The "capabilities" attribute might
not have been provided a value after the "initialized".
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Avoid potential NPE

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
Improve performance by getting the document one for each resource
instead of several times: one for each new diagnostic (when calling
computeMarkerAttributes when creating the marker), once for each updated
diagnostic (when calling updateMarker for markers to update).
=> Improve performance by getting the document one for each resource

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/console/DSPStreamsProxy.java
Resolves `// TODO args.setFrameId(0);` for `EvaluateArguments` requests, in turn fixing https://github.com/castwide/readapt/issues/11.
=> [Debug] Add frameId to EvaluateArguments request

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
Lazy check for the existence of a resource, as we already checked that
the resource exist before calling updateMarkers.
Instead, if the resource has ceased to exist between the point we call
updateMarkers and the point where we create/update the markers, catch
the CoreException and ignore it.
=> Lazy check for the existence of a resource

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
This prevents the following NPE on shutdown:
```python
java.lang.NullPointerException
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Un …
```
=> Prevent NPE in SymbolsLabelProvider.dispose()

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
`ResourcesPlugin.getWorkspace().run(runnable, new NullProgressMonitor());` executes the job with a resource lock on the whole workspace which can result in interruption of auto build jobs of non-related projects at https://git.eclipse.org/c/platform/eclipse.platform.resources.git/tree/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/resources/Workspace.java#n2262
=> Run updateMarker job with lock on specific resource only

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/UriToResourceAdapterFactory.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
Support linked files in IFileBufferListener by using LSPEclipseUtils#toUri, which will call an adapter to map the IResource to an URI.
=> Support linked files in IFileBufferListener

org.eclipse.lsp4e/META-INF/MANIFEST.MF
As a continuation of https://github.com/eclipse/lsp4e/pull/83, we need to export org.eclipse.lsp4e.operations.codeactions so that it is possible to register org.eclipse.lsp4e.operations.codeactions.LSPCodeActionMarkerResolution as marker resolution generator for the marker type with the extended attributes.
Otherwise, the new marker will not generate any marker resolution.
=> Export org.eclipse.lsp4e.operations.codeactions

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/linkedediting/LinkedEditingTest.java, org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockTextDocumentService.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingBase.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingReconcilingStrategy.java
LinkedRditingRange's wordPattern value is used to control the linked editing. The value of the wordPattern is to be provided
by the active LS, otherwize a common Unicode Indentifier  pattern is used to validate the input.
Change-Id: I6291f7136fbdb8f4ee3f067d8b17c74400067676
=> Linked editing doesn't exit on whitespaces and other non-word chars #94

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
In Eclipse workspace it is possible that a single file corresponds
to multiple workspace resources. This typically arises in 'multi-project'
setups where both the parent project and its nested children are
imported into the workspace.
This creates all sorts of confusions and subtle bugs.
The logical solution seems to be to deliberatly choose the
'most nested' resource instead of just arbitarily picking the
first one found.
This small PR does just that in LSPEclipseUtils.
This indirectly fixes issues in STS such as:
https://github.com/spring-projects/sts4/issues/769
https://github.com/spring-projects/sts4/issues/747
cc @BoykoAlex
=> Choose 'best' resource when file url is ambiguous

org.eclipse.lsp4e.jdt/META-INF/MANIFEST.MF, org.eclipse.lsp4e.jdt/plugin.xml, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LSJavaCompletionProposalComputer.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LSJavaProposal.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LspJavaQuickAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/command/CommandExecutor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionCompletionProposal.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionsMenu.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java
1. Support `codeAction/resolve` for edit property
2. LS based Quick Assist processor for Java editor
3. Single undo operation for WorkspaceEdit (UndoManager was missing from the apply operaion)
4. Bugs in `LSPCodeActionQuickAssistProcessor`
- Can't cache range. Each subsequent invocation of QA in the same doc different location brings up the same cached proposals
- Don't think caching proposals is a good idea. Computation method can be reentrant but not recursive. Problem is old proposals are never cleared. I might be misunderstanding this bit though...
=> Java editor LS Quick Assist

org.eclipse.lsp4e.test/fragment.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServiceAccessorTest.java, org.eclipse.lsp4e/schema/languageServer.exsd, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServersRegistry.java
In https://github.com/eclipse/lsp4e/pull/92 we introduced the possibility of initializing server before the user open a file in the editor, as a related functionality, we introduce the possibility of keeping the server running even if the last connected document is disconnected.
The reasoning is similar as in that PR: our language server will setup some state and do an initial build (The initial build in our case just loads the precomputed state and will publish the markers of this state to the user, that is different to the eclipse target) on initialization, and this is time consuming. In addition to start the LS upfront, we also want to keep it running even if editors are closed.
=> Add stopOnLastDisconnectedDocument configuration property

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java
There are many various refactorings returned from the LS. However, CodeActions are fetched in the context of showing Quick Fixes (i.e. problem marker hover) then only QuickFix kind of CodeActions are applicable and the rest ignored.
=> Only use Quickfix kind of CodeActions for Quickfixes

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPLaunchDelegate.java
Some process (eg node-debug2) are not responding well to a gentle
"destroy" and often remain as zombies. Let's "destroyForcibly" instead.
=> Use destroyForcibly for debug process

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
There is a recent commit is LSP4J - Move runInTerminal #620 (eclipse/lsp4j@bdabc77) - that moves `runInTerminal` method
declaration from IDebugProtocolServer to IDebugProtocolClient in LSP4J.
So an according change is expected to be made in LSP4E's DSPDebugTarget as it implements IDebugProtocolClient, because until it's not,
we'll have runInTerminal to appear twice when finding for the RPC methods, which generates the mentioned `IllegalStateException:
Duplicate RPC method runInTerminal.` exception preventing a debug launch from being started.
Change-Id: I487f9f492c622601f3eb047c6016d63141877c55
=> Fix for IllegalStateException: Duplicate RPC method runInTerminal.

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServiceAccessorTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/color/ColorTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/IncompleteCompletionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/definition/DefinitionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/diagnostics/DiagnosticsTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/documentLink/DocumentLinkTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidChangeTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidCloseTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidOpenTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidSaveTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/hover/HoverTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/OutlineContentTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/rename/LSPTextChangeTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/rename/RenameTest.java
in place of File.createTempFile, so we are sure the file gets cleared
and don't have to deal with cleanup as part of the test (done in the
AllClentRule)
=> Testing: use TestUtils.createTempFile

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatter.java
If the server sends back a bad location then it may be that the server's and the client's view of a document have
got out of sync. Abort set of changes rather than risk applying nonsensical changes and corrupting the document.
Split out of preceding commit following review.
=> concurrency: Bail out of changes if inconsistency detected

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/pom.xml
=> handlers: Use activeWhen rather than enabledWhen consistently and scope

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java
Ran into this one with the new support for DocumentWillSaveWaitUntil. Our language server doesn't support it yet and is not setting anything for the server capability rather than sending 'false'. I think this is legal as it's an optional property, so just need to handle the possible null.
=> WillSaveWaitUntil: Handle null for optional boolean server capability

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
LanguageServerDefinition, IPath) when the project is null and there are
started language server wrappers.
=> Remove NPE in LanguageServiceAccessor.getLSWrapper(IProject,

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
by not connecting the file where we retrieve marker information. That is
an unnecessary step which can be expensive (for example the Xtext
language server rebuilds the source) and causes timeouts on
checkMarkerResoultion
=> Improve marker resolution performance

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServiceAccessorTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/RunningLanguageServerTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/TestUtils.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/color/ColorTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/AbstractCompletionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/CompleteCompletionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/ContextInformationTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/IncompleteCompletionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/definition/DefinitionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/diagnostics/DiagnosticsTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/documentLink/DocumentLinkTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidChangeTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidSaveTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentRevertAndCloseTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentWillSaveWaitUntilTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/format/FormatTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/highlight/HighlightTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/hover/HoverTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/linkedediting/LinkedEditingTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/operations/codelens/LSPCodeMiningTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/references/FindReferencesTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/rename/RenameTest.java
This PR:
1. Removes TestUtils.getTextViewer and replaces its usage with LSPEclipseUtils.getTextViewer
2. Improves RenameTest stability
3. Improves LanguageServiceAccessorTest stability and comprehensibility
=> Improve tests

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServersRegistry.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
This is my proposal to address the dead lock issues reported via #161 and #22.
The deadlock occurs when `LSPFoldingReconciler` or `CodeMiningReconciler` are triggered in background threads at the same time when text is modified in the UI thread.
Both executions end up in acquiring a lock on the `SynchronizableDocument` as well as on the `LanguageServiceAccessor.startedServers` field. Unfortunately in case of the Reconcilers first the lock on the `startedServers` field is acquired and then some underlying internal Eclipse platform code tries to get a lock on the document, whereas in case of text modifications in the UI thread first the document gets locked and then it is attempted to acquire the `startedServers` field. Because of race conditions this can lead to deadlocks.
Here is an …
=> LanguageServiceAccessor: Rework thread-safe access to startedServers to prevent dead locks

org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java
when the map entry is created, not to 100, which would mean that the job has been already done.
=> initialize currentPercentageMap with 0

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/OpenDeclarationHyperlinkDetector.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/DocumentLinkDetector.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/LSPTextHover.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSFindReferences.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceDialog.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/WorkspaceSymbolsQuickAccessProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java
If the server is not responsive enough logging errors without any other
context than a stacktrace looks to the end user a bit scary, as if the
IDE would be broken.
Instead reporting a warning with a message that explains the context and
include the timeout that was not met.
=> Improve logging of java.util.concurrent.TimeoutException

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
We get random `ConcurrentModificationExceptions` when running with json wire logging (via setting `org.eclipse.lsp4e/debug` to true), e.g.:
We thought these might be the smoking gun for a bug we were investigating, but I think they're an artifact of the toString() method traversing collections while the ultimate endpoint message consumer may be mutating (e.g. by sorting) the message.
These turn up a fair bit when running our integration tests with this tracing turned on, and go away when these two lines are swapped (`logMessage()` is fully synchronous, while `consumer.consume()` might well not be).
=> Fix suspected concurrency bug in debug logging

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameHandler.java
It is possible to have an ITextEditor implementation that can return an ISelectionProvider from getSelectionProvider() that is null as the ITextEditor API specification doesn't forbid returning null  (though the preferred base of AbstractTextEditor doesn't happen to normally do so and if implementing AbstractTextEditor it makes a non-null assumption...)
=> Update LSPRenameHandler to not NPE

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java
The method checkInitialConditions was handling the error using an status
which was never returned. In addition the method handleError was
returning a value which was never used.
Both problem has been fixed by removing handleError and adding a method
that just gets the error message. This makes more clear where this error
message is attached. The error handling of checkInitialConditions has
been then fixed accordingly.
=> Fix lost error message checkInitialConditions

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
for Errors when creating untitled text files #147
the content type may be based on path or file name pattern or another subsystem via the ContentTypeManager so that is not necessarily an error condition
=> getDocumentContentTypes to ignore FNFE

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/AllTests.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/IncompleteCompletionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/VariableReplacementTest.java, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java
for completion proposals. Just ${var} or $var, without tab stops, choice
nor linked edition.
Fixes https://github.com/eclipse/lsp4e/issues/204
=> Implement basic variable substitution

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/Messages.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/messages.properties
by showing a notification (vanishing pop-up on the bottom right corner) and
increasing the default timeout from two to five seconds
=> Improve user feedback when on save actions timeout

org.eclipse.lsp4e/src/org/eclipse/lsp4e/ServerMessageHandler.java
Caused by long standing SWT issue (
https://bugs.eclipse.org/bugs/show_bug.cgi?id=194758 ) but easily
workaroundable as done in this patch.
Some minor SonarLint warnings are also fixed.
Fixes https://github.com/eclipse/lsp4e/issues/220 .
=> Make sure LSP notification message is wrapped

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
This change allows LSP4e to cope with a language server that sends URIs for UNC paths on an unmapped network drive in the modern [Microsoft preferred] way, using the authority to convey the server name.
I.e. `\\myserver\myshare\path\to\file` can be accepted in the newer, preferred syntax `file://myserver/myshare/path/to/file` rather than `file:////myserver/myshare/path/to/file`. The traditional `java.io.File` class will only generate and accept URIs in the legacy format, but `java.nio.file.Paths` will accept either and generate the former.
Changing LSP4e to generate the newer syntax would risk breaking any language servers built in Java, and furthermore caused some internal breakages where we convert `File`s to `URI`s and back again. There are, however, only a couple of places that …
=> UNC paths: Support preferred UNC URI syntax on Windows

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/LSPLineContentCodeMining.java
Fix check of capability of resolve inlay hint.
This current support of inlay hint consider that if language server supports inlay hint and not resolve inlay hint, it support resolve inlay hint and consume the LSP resolveHint (and language server throws an excption which says that it doesn't support the resolve of inlay hint).
This PR fixes this problem.
=> Fix check of capability of resolve inlay hint.

org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconciler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java
textDocument/documentLink should be renderered with hyperlink style.
Fixes #126
=> textDocument/documentLink should be renderered with hyperlink style.

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/TestUtils.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
Hello,
I will try to be the most precise possible.
The issue exhibited here only happens when the eclipse workspace contains a file accessible from more than one project which is a common case when working on maven multi modules projects (i think gradle multi modules projects are also impacted but i did not check)
Eclipse workspace with 2 projects : parent_project, nested_project
Where nested_project is contained in parent_project
```
parent_project
|
-- nested_project
|
-- file.ext
nested_project
|
-- file.ext   
```
With this kind of workspace, we have two cases:
- When the projects presentation is "Hierarchical", the file edited is the most nested and the method LSPEclipseUtils.findResourceFor(uri) will return the correct IResource (provided the function LSPEclipseUtils.findMostNested …
=> LSPEclipseUtils.findMostNested now returns the most nested project

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
This change enables custom language clients to control which workspace folders are send to the language server `initialize` request and during `workspace/didChangeWorkspaceFolders` event by overriding the `workspaceFolders` method.
E.g.
```java
class MyLanguageServerClientImpl extends LanguageServerClientImpl {
@Override
public CompletableFuture<List<WorkspaceFolder>> workspaceFolders() {
return CompletableFuture.completedFuture(
allProjectsWithNature("my.project.nature").stream() //
.map(LSPEclipseUtils::toWorkspaceFolder) //
.collect(Collectors.toList()));
}
}
```
Without this change the `initialize` request will always contain all workspace projects no matter if they are relevant for the LS or not.
This also means the LS requests configuration settings for all projects via …
=> Allow limiting the workspace folders for a language server

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
If the debugProtocolFuture is running the message loop on the same thread we are in currently, the cancel call will set the interrupt flag. That isn't necessary as the message loop isn't waiting on anything (since this code is running). The interrupt flag may affect future processing, like terminating processes. Therefore clear the flag.
Fixes #264
=> Clear interrupt flag after cancelling message read thread

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/LSBasedHyperlink.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/DocumentLinkDetector.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/FocusableBrowserInformationControl.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/WorkspaceSymbolQuickAccessElement.java
Provide new signature to open URI without UI.getActivePage()
This PR provides new methods in LSPEclipseUtils without having IWorkbenchPage as parameter. The benefit with that is:
* it simplifies a little the code.
* it allows for another plugin to use open methods without redefining an utility class UI.getActivePage() since UI class is not exported.
=> Provide new signature to open URI without UI.getActivePage()

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/LSPCodeMining.java
The LSP command of command can be never null https://github.com/eclipse/lsp4j/blob/5605ca82252833777dbef82ca13a403dbfb9d906/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/Protocol.xtend#L2318 so it means that Codelens should check too if the command is not empty to execute it.
In other words if the command of command is emprt, CodeLens will not be clickable. It will fix for instance the following error with XML https://github.com/eclipse/wildwebdeveloper/issues/644
=> Check if LSP command is not empty to perform CodeLens action

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/SymbolsLabelProviderTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
In this change the SymbolLabelProvider is extended to show the detail string that is part of the DocumentSymbol response.
Addresses  #250.
Signed-off-by: Gerd Grossmannn <gerd.grossmann@avaloq.com>
=> Show DocumentSymbol.Detail in Outline View

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/UI.java
Adresses #123
Draft of a possible solution. Reflection pieces can be substituted by the new API added to eclipse platform ui text. However, the first step is to check whether this is something we may use as starting point to carve the final solution.
cc: @martinlippert @mickaelistria
Note: Changes to LSPCodeActionQuickAssistProcessor are unrelated to the issue but i feel they are common sense fix to the existing implementation.
=> Update Quick Fixes in the UI once computed

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java
This should prevent this exception from happening:
java.lang.NullPointerException
at org.eclipse.lsp4e.LSPEclipseUtils.toCompletionParams(LSPEclipseUtils.java:183)
at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:94)
at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:352)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:351)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
at …
=> Prevent NPE in LSContentAssistProcessor.computeCompletionProposals

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java
java.lang.NullPointerException Cannot invoke "java.util.List.iterator()" because "links" is null
at org.eclipse.lsp4e.operations.documentLink.LSPDocumentLinkPresentationReconcilingStrategy.underline(LSPDocumentLinkPresentationReconcilingStrategy.java:92)
at org.eclipse.lsp4e.operations.documentLink.LSPDocumentLinkPresentationReconcilingStrategy.lambda$5(LSPDocumentLinkPresentationReconcilingStrategy.java:83)
=> Fix NullPointerException

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
This PR adds the ability to parse the fragment of a URI to determine the appropriate range in a document. This allows to navigate within a document from e.g. a hover that contains URIs.
The following formats are understood:
```
file://path/to/file#L34,1-L35,3
file://path/to/file#34,1-35,3
file://path/to/file#L34,1-35,3
file://path/to/file#L34
file://path/to/file#L34,1
```
=> Allow to navigate from a URI to a range within a document

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
Some language servers may send diagnostics for resources that are not accessible (eg closed).
Do not fail in such case.
=> Do not fail on non-accessible resources

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LoggingStreamConnectionProviderProxy.java
[t=1667223932171] LSP4E to ...:
For debugging and readability this is not useful, as usually one would like to correlate logs from the client and the server, instead use the standard:
[2022-11-29T13:20:11.220291200+01:00] LSP4E to ...:
Also use a `StringBuilder` directly to create the message instead of creating a new `String` with the payload and then adding that to other strings with `+`. Thus we avoid one `String` creation.
=> Currently the log is using currentTimeMillis, see below

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidChangeTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
See https://github.com/eclipse/lsp4e/pull/318#issuecomment-1330738521 and following comments. Usage of *Async is mandatory to prevent from blocked threads so far.
=> Revert change and re-use then*Async

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CommandMarkerResolution.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java
Improve on 89dc090203e9a1fd2c07926d0579a1eff303fc44  to avoid calling LSPEclipseUtils.getDocument(resource) when
LSPEclipseUtils.getExistingDocument(resource) already returned a resource, as it is a bit wasteful to run through the same code twice.
=> avoid calling LSPEclipseUtils.getDocument(resource) when we already have a document

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LoggingStreamConnectionProviderProxy.java
Use UTF-8 encoding explicitly so that users who are using regional
charset by default don't end up with corrupted messages, or worse
unhandled exceptions thrown here.
According to the LSP specification:
"The content part is encoded using the charset provided in the
Content-Type field. It defaults to UTF-8, which is the only encoding
supported right now. If a server or client receives a header with a
different encoding than UTF-8 it should respond with an error."
So even though the code in LSP4J reads the Content-Type header and
evaluates it, and it could thus supports different encoding, LSP4E does
not need to support it, and in practice, no server should use that
either.
=> Fix encoding

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java
Fix #355 
`org.eclipse.jface.text.quickassist.QuickAssistAssistant` line 71 creates `TextInvocationContext` with `length` equal to `-1` - therefore length -1 is valid.
Now LSP4E just adds length to get the last position. Need to account for negative length,
=> Fix BadLocationException for length==-1

.github/dependabot.yml
Separated roots are subject to be replaced with the single '/'-root directory as soon as https://github.com/dependabot/dependabot-core/issues/4364 issue is fixed. Until then no version check for the root project ('/pom.xml')
=> Temporary fix for dependabot setup

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java
Fixes
```java
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.eclipse.lsp4j.jsonrpc.messages.Either.getLeft()" is null
at org.eclipse.lsp4e.operations.semanticTokens.SemanticHighlightReconcilerStrategy.hasSemanticTokensFull(SemanticHighlightReconcilerStrategy.java:200)
at org.eclipse.lsp4e.LanguageServiceAccessor.lambda$15(LanguageServiceAccessor.java:597)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
```
=> Fix NPE in SemanticHighlightReconcilerStrategy#hasSemanticTokensFull

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/Messages.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/messages.properties
Currently when something unexpected happens in the communication between LSP4E and a Language Server, never ending "Language Server Background Job" entries appear in the progress view.
This PR replaces the label "Language Server Background Job" with the actual name/label of the language server, which simplifies troubleshooting and helps end-users to isolate the offending plugin.
Before:
After:
=> Use language server label as background job name if available

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/MockConnectionProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
This PR attempts to mitigate some of the behaviour noted in https://github.com/eclipse/lsp4e/issues/371
I have picked through the code and checked the documentation on `Executors.newCachedThreadPool()` and established that the behaviour is probably benign as far as production goes: prior to this PR we created a new cached thread pool for each LS every time `LanguageServerWrapper.start()` was called, with no corresponding cleanup code.
However:
1. Only one thread is ever instantiated from each thread pool by the launcher (used for listening for LS responses and incoming server->client requests)
2. As documented [here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/Executors.html) `Executors.newThreadPoolExecutor()` creates threads on demand and shuts them …
=> Improve thread cleanup/recycling in tests

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/command/CommandExecutor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionsMenu.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/CodeLensProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/color/DocumentColorProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/OpenDeclarationHyperlinkDetector.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/DocumentLinkDetector.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatter.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/highlight/HighlightReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/InlayHintProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingBase.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java
This PR replaces `URI#toString()` calls with `URI#toASCIIString()` calls, either directly or indirectly by using the new `LSPEClipseUtils#toTextDocumentIdentifier` methods to construct `TextDocumentIdentifier` instances.
This addresses https://github.com/eclipse/lsp4e/issues/358
=> Use fully quoted/encoded URIs via URI.toASCIIString() #358

org.eclipse.lsp4e/src/org/eclipse/lsp4e/ConnectDocumentToLanguageServerSetupParticipant.java
The SUBMITTED_JOBS was introduced to help test teardown so that we can cancel any of these jobs if the test finishes before they have a chance to run. Wasn't clearing out the map on all paths.
Addresses https://github.com/eclipse/lsp4e/issues/377
=> Test teardown - make sure global object is cleaned out on all paths

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
There are Language Servers that will send a TextEdit response on format, despite the fact that the formatting did not change.
This results in the open editor being marked dirty.
This PR only applies a TextEdits to a document if it would actually change the text avoiding editors being marked dirty despite no change.
=> Only apply TextEdits if they change the document content.

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServersTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/LSPTextHover.java
Based on code originally submitted in #333  - this ports `LSPHover` to use the new API. Note that there is no timeout code in the revised logic, because there is no intermediate future exposed [the call to getLanguageServer is now rolled up into internal logic], but this should be fine as the consuming code in `getHoverRegion()` incorporates the timeout.
The API already excludes any nulls from the returned list, so that post-processing step is no longer needed here either.
Have tested it manually using the Corrosion plugin as well.
=> New api - port hover

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServersTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java
Also rename the executors to remove abbreviations.
=> Reduce public API introduced by new API.

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
Use getLineOffset instead of getLineInformation().getOffset() as it returns the same offset without the creation of an intermediate IRegion object.
Since DiagnosticsTest.testDiagnosticsRangeAfterDocument test that diagnostics outside of the document range are published with range start/end equals to the document length, and getLineOffset has an extra consistency check over getLineInformation().getOffset() which throws BadLocationExection, we need to handle this case when computing marker attributes.
=> Use getLineOffset instead of getLineInformation().getOffset()

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceDialog.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceHandler.java
This reworks onto the merged version of the new API example code originally submitted in #333 
Note that the Workspace Symbols dialog is currently not rendering and hot-linking correctly because of changes to the LSP spec. Originally attempted to fix this as well in #423 but not strictly related to the new API so have agreed to submit the API port in this PR as a standalone change.
@rubenporras FYI
=> New API: Port workspace symbols

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
This was originally submitted as part of porting Workspace symbols to the new API (now submitted standalone).
In the process of doing the port I realised that the Workspace Symbols dialog appears to have been broken some time ago: the code to call the server was upgraded to handle the newer return type, and indeed to convert any legacy `SymbolInformation` instances returned into the newer `WorkspaceSymbol` lsp4j type, but the UI code was still assuming the objects could be downcast to `SymbolInformation`.... the two types are not directly interconvertible.
I've got it working but the unit test could do with upgrading. I was also unsure what else used the old `SymbolInformation` code branches and whether I could get rid of it. Can anyone comment?
=> Fix Workspace Symbols Dialog

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/operations/codelens/LSPCodeMiningTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/CodeLensProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/LSPCodeMining.java
Ports code lenses across to the new API. Hopefully a straightforward change.
=> New API: Port code lenses

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java
The LS protocol now allows (and indeed prefers) a WorkspaceEdit to consist of DocumentChanges instead of Changes. Some old code was assuming that if there were no Changes then there was nothing to do. This mean a load of spurious 'no edits' warnings in the UI before the rename succeeded anyway.
Split out of #459 as not strictly related to the API port
@rubenporras FYI
=> Rename: Fix issue with rename wizard

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java
@rubenporras this was a comment I made on #454 that I think arrived too late for you to notice.
If connect fails or returns null, then we should return null also in this method, not wrapper.
It's actually quite hard to provoke this error path when wrapper is not itself null, but for paranoia's sake I think we should still correct the logic here.
=> New API: covariantly return null on failure path

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/rename/RenameTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameProcessor.java
Ported rename to the new API. We need to make a slightly arbitrary choice of LS in the (fairly unlikely, in practice) case where more than one LS could do the rename. The old logic just picked the first LS that supported rename; I've changed this  slightly to pick the first LS that responds to the prepareRename phase and stick with that one.
I ran into some logic that had not been updated to account for the fact that `WorkspaceEdit`s can now consist of `DocumentEdit`s rather than `Edit`s, so have fixed that.
=> New api: port rename

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/LSBasedHyperlink.java
Add URI to the Hyperlink label as default case, since the protocol supports returning several locations for all schemas, we need to be able to present them on the UI in a way which they can be distinguished, in case there is more than one.
=> Add URI to the Hyperlink label as default case

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java
In LemMinx we have a CodeAction which is used to generate an XSD/DTD/RNG file which returns:
* a null text edit
* a custom command which generates the grammar file
When code action is resolved, the LemMinx language server return null, because there are nothing to resolve. After that there is an NPE at https://github.com/eclipse/lsp4e/blob/91e9977a57afe0a6d4bd65fbc499551f3cabbd2f/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java#L78
This PR update the code action only if resolve return a non null code action.
=> Fix NPE of CodeAction when resolve from ls return null.

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java
This should avoid using Executors in cases where different executors should be used.
=> Make filter and serverId unchangeable once they have been set.

org.eclipse.lsp4e/src/org/eclipse/lsp4e/progress/LSPProgressManager.java
Partially address #504  - the last part of it.
I can submit the full PR for #504. Essentially the total work for the progress would be hardcoded to 100 and the begin message percentage would be assumed 0 if it is a non null integer.
=> Allow progress report messages to be applied for indefinite progress

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/StyleUtil.java
This class could be running/initialized in non-UI Thread and the asyncExec can be blocked for a longer time.
Besides, colors are usually not the best way to emphasize on some semantics, a cross-out is clear enough.
=> Use only cross-out for obsolete element

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java
Quick fixes for a problem marker shown fine if there are quick fixes available. However, if there are no quick fixes available an empty list of code actions is received on the lsp4e side. However, this result is ignored (this the chunk of code is changed by this PR) and therefore Computing... is shown indefnitely under quick fixes for problem that don't have a quick fix.
=> Handle empty quickfix list

org.eclipse.lsp4e/plugin.xml
Fixes #38
`LSPSymbolInWorkspaceHandler.setEnabled(Object)` for updating the enable status will only be called by the framework when the bundle org.eclipse.lsp4e is active.
Without the now introduced check for `bundleState=ACTIVE` the conflicting key binding will not be filtered out by method `KeyBindingDispatcher.getExecutableMatches(KeySequence, IEclipseContext)` in bundle `org.eclipse.e4.ui.bindings`.
Before Eclipse Release 2022-12 the conflicting key binding for `Shift+Ctrl+T` didn't show up, because the bundle `org.eclipse.lsp4e` was always activated by a startup extension in `plugin.xml` and that is why conflict resolution in the `KeyBindingDispatcher` has worked. The use of this extension has been removed with a0dd75aeb405986e187c9a2b1325144e2afa9273. (Bundle activation status can …
=> Enable LSPSymbolInWorkspaceHandler only if LSP4E bundle is active

CONTRIBUTING.md
The old URL [https://download.eclipse.org/lsp4e/latest/](https://download.eclipse.org/lsp4e/latest/) no longer exists.
=> Software site URL for snapshot builds updated

org.eclipse.lsp4e/plugin.xml
Limiting the applicability of the key binding for the Rename command with ID `org.eclipse.ui.edit.rename` to the _Generic Text Editor_ reduces conflicts with commands from other plug-ins using the same key combination (e.g. `org.eclipse.jdt.ui.edit.text.java.rename.element` from JDT UI).
=> Limit the key binding Shift+Alt+R for Rename to the Generic Text Editor

org.eclipse.lsp4e/src/org/eclipse/lsp4e/ConnectDocumentToLanguageServerSetupParticipant.java
When requested too early during document initialization, resolution of Document to URI is failing. So we add a delay to let document complete initialization.
Fixes https://github.com/eclipse/lsp4e/issues/560
=> Delay document->LS connection

org.eclipse.lsp4e/plugin.properties, org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/SupportedFeatures.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/selectionRange/LSPSelectionRangeAbstractHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/selectionRange/LSPSelectionRangeDownHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/selectionRange/LSPSelectionRangeUpHandler.java
Support for textDocument/selectionRange
Fixes #561
=> Support for textDocument/selectionRange

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/LSPDocumentAbstractHandler.java
the format action is disabled in the `pom.xml` editor since some refactorings and changes to the action handlers. The underlying reason why the actions are disabled in the `pom.xml` editor is because the new abstract handler doesn't take multipart editors into account.
=> ask for active editor directly to deal with multipart editors

org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockTextDocumentService.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
In Eclipse, we set a minimal range of 1 character, even for diagnostics that have an empty range (just a position); so this fixes ensure such markers and diagnostics are still matched together upon update, to avoid re-creating diagnostics.
=> Match diagnostics with empty ranges

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/codeactions/CodeActionTests.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionsMenu.java
Code actions cannot be performed on read only sources, so there is no need to ask the language server for them.
=> Prevent code actions on read only sources.

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LaunchConfigurationStreamProvider.java
the code nicely handles the situation by checking the queue again.
=> remove error from the log when the sleep during read is interrupted, as

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/TestUtils.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/OutlineContentTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsModel.java
Fixes #638
Since there is no IFile object for a file outside the workspace, replaced
IFile by IDocument in DocumentSymbolWithFile. Maybe rename DocumentSymbolWithFile into DocumentSymbolWithDocument?
=> [#638] Fix outline view for external files

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsModel.java
Since URI is more generic than IDocument this type should be preferred. Its not possible to get the URI or IFile of an IDocument by using the static helper methods in LSPEclipseUtils when the IDocument is not opened in an editor (buffer is null then). There are use-cases where it makes sense to use a DocumentSymbolWithFile object when the document is not opened in an editor (e.g. in an content provider for the project explorer view).
=> Use URI instead of IDocument for DocumentSymbolWithFile

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsModel.java
The `DocumentSymbolWithFile#file` property has been removed from the public API without undergoing any deprecation period. We are currently using this property in Dart4E and Haxe4E, and require a transition phase.
=> re-add DocumentSymbolWithFile#file property removed by #639

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
Changes LSPDiagnosticsToMarker to consider subtypes of the specified markerType so it is possible to customize the marker type based on diagnostic attributes (e.g. in a workspace change listener).
See issue #645.
=> LSPDiagnosticsToMarker: Handle subtypes

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java
JDT.ls uses custom protocol for sources coming from jvm/jar files (e.g. jdt://contents/java.base/java.lang/Appendable.class?=proba/%5C/usr%5C/lib%5C/jvm%5C/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/17%5C/docs%5C/api%5C/=/%3Cjava.lang(Appendable.class ) which is retrievable from ITextFileBuffer if/when custom EFS for the protocol is provided.
Extra change was required in LSPEclipseUtils.getDocument(URI) which wrongly assumed that every IDocument has to be backed by file.
=> Make Outline view works for documents with custom URI

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/FocusableBrowserInformationControl.java
Fixes #650
FocusableBrowserInformationControl expects to receive HTML with a HEAD element. However, this isn't always the case - in fact, the input could be plain text with minimal decorations from LSCompletionProposal.getAdditionalProposalInfo().
When no HEAD element is provided, FocusableBrowserInformationControl displays raw HTML in the completion proposal detail pane (see https://github.com/eclipse/lsp4e/issues/650).
This pull request addresses the situation where the HTML input doesn't contain a HEAD element by prepending a new HEAD to the input.
=> [#650] Handle HTML without HEAD

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/highlight/HighlightReconcilingStrategy.java
I realized that "mark occurrences" was not working (at least with the Haxe and Dart Language Servers).
The reason are silently swallowed NPEs in the HighlightReconcilingStrategy. Adding two null guards restored the functionality.
=> Fix "mark occurrences" not working because of NPE

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/ContentTypeToLanguageServerDefinitionTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServersTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/linkedediting/LinkedEditingTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/OutlineContentTest.java, org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockTextDocumentService.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServersRegistry.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionQuickAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/CodeLensProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/WorkspaceSymbolsQuickAccessProvider.java
Simpler code than collect(Collectors.toList())
=> Use Stream.toList method

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/SymbolsLabelProviderTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
Use "strike-trough" just like in completion popup. Implementation supports both the deprecated getDeprecated (where applicable) and the new getTags way.
Fixes https://github.com/redhat-developer/eclipseide-jdtls/issues/77
=> Annotate deprecated symbos in outline

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
Multiple Timer threads can be left running if
LanguageServerWrapper.startStopTimer() runs in parallel with LanguageServerWrapper.removeStopTimer() or another startStopTimer(). We prevent this issue by reducing the Timer threads created down to one, and then only scheduling or cancelling TimerTasks on that Timer thread synchronously.
This should fix issue #644.
=> Perform updates to Stop Language Server Timer synchronously.

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java
=> fix: adhere to lsp spec when calculating offsets

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java
The edits must be applied while running in UI thread, else an `InvalidThreadAccess` exception is thrown.
=> fix: run apply edits in UI thread

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServiceAccessorTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/commands/DynamicRegistrationTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidChangeTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidCloseTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidOpenTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidSaveTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentEditAndUndoTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentRevertAndCloseTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentWillSaveWaitUntilTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
Removal of all APIs that expose the language server object.
The test LanguageServiceAccessorTest.testStatusHandlerLSAsRunConfiguration
has been deleted as it cannot be reliably tested, it depends on creation
of the stream provider in LanguageServerWrapper#start, which happens in
a background thread.
The method LanguageServerWrapper#getVersion has been renamed and made public as a
replacement of the marked for removal class `LSPDocumentInfo`, which can be used to
indirectly get access to the until now private method.
=> Removal of all APIs that expose the language server object.

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServerWrapperTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
=> Synchronize LanguageServerWrapper.isActive() (#690)

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/OutlineContentTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/outline/SymbolsLabelProviderTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileDialog.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/CNFOutlinePage.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/OutlineSorter.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsModel.java
This field finally removes the `DocumentSymbolWithFile#file`.
Outline view performance on large files may also improve if the file is removed as I am currently seeing a lot of this in thread dumps when the UI freezes when opening VERY large JSON files.
```python
java.lang.Thread.State: RUNNABLE
at java.io.WinNTFileSystem.canonicalize0(java.base@17.0.6/Native Method)
at java.io.WinNTFileSystem.canonicalize(java.base@17.0.6/WinNTFileSystem.java:462)
at java.io.File.getCanonicalPath(java.base@17.0.6/File.java:626)
at org.eclipse.core.internal.utils.FileUtil.canonicalPath(FileUtil.java:66)
at org.eclipse.core.internal.utils.FileUtil.canonicalURI(FileUtil.java:161)
at org.eclipse.core.internal.localstore.FileSystemResourceManager.allPathsForLocation(FileSystemResourceManager.java:67)
at …
```
=> remove deprecated DocumentSymbolWithFile#file field

org.eclipse.lsp4e/src/org/eclipse/lsp4e/ConnectDocumentToLanguageServerSetupParticipant.java
This PR fixes an erratic  ConcurrentModificationException that results in random test failures.
```java
java.util.ConcurrentModificationException
at java.base/java.util.WeakHashMap.forEach(WeakHashMap.java:1031)
at org.eclipse.lsp4e.ConnectDocumentToLanguageServerSetupParticipant.waitForAll(ConnectDocumentToLanguageServerSetupParticipant.java:67)
at org.eclipse.lsp4e.test.AllCleanRule.clear(AllCleanRule.java:66)
at org.eclipse.lsp4e.test.AllCleanRule.finished(AllCleanRule.java:58)
at org.junit.rules.TestWatcher.finishedQuietly(TestWatcher.java:122)
```
=> fix erratic ConcurrentModificationException during unit tests

pom.xml
This PR prevents local (i.e. developer workstation) maven builds from failing if uncommitted changes are present.
=> allow local maven builds with dirty working tree

org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/NoErrorLoggedRule.java
This PR extends logging output for easier root cause analysis of erratic test failures esp. if happening on remote build servers
=> improve error logging for JUnit tests

org.eclipse.lsp4e/pom.xml
The lsp4e.plugin module was configured to unnecessarily re-download js/css files from a CDN on each build invocation.
This PR changes the logic to only download/overwrite the files locally if they are missing or outdated.
This makes running `mvn --offline verify` possible and generally speeds up local maven builds.
=> fix maven offline builds

pom.xml
See https://github.com/eclipse-tycho/tycho/blob/61925ee127cecfe13efff467817aedbb50e24168/tycho-extras/tycho-p2-extras-plugin/src/main/java/org/eclipse/tycho/plugins/p2/extras/CompareWithBaselineMojo.java#L118-L122
=> fix Maven Warning "Parameter 'comparator' is read-only, must not be used in configuration"

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/console/DSPProcess.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServerWrapperTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LaunchConfigurationStreamProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LoggingStreamConnectionProviderProxy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/server/ProcessStreamConnectionProvider.java
This PR adds the `LanguageServerWrapper#getProcessHandle()` method and enriches the the `LanguageServerWrapper#toString()` info with the pid of the underlying LS process.
The `LanguageServerWrapper#getProcessHandle()` will also be useful when implementing a LanguageServers UI view to access information such as pid, working directory or command of the underlying LS process.
=> add LanguageServerWrapper#getProcessHandle()

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/typeHierarchy/TypeHierarchyView.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/typeHierarchy/TypeHierarchyViewContentProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/typeHierarchy/TypeMemberContentProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/messages.properties
When the type is declared in an external file, then the IDocument object for this file has to be created and opened. Then the symbols can be fetched form this file via LS.
fixes #775
=> fix missing member from types in external file

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/references/FindReferencesTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSSearchQuery.java
Related to [discussion 784](https://github.com/eclipse/lsp4e/discussions/784)
Very small changes to fix the `references` operation not displaying the correct line number in the Search window in eclipse, see the discussion for examples. I've also modified the references test to verify the lines are stored correctly.
=> Fix References Displaying Incorrect Line Number in Search Panel

CHANGELOG.md
We are not really using the changelog anymore and most of the valuable information is provided in the github releases page, therefore link to the releases page from the changelog so that people who look at the changelog will find the most recent information
See https://github.com/eclipse/lsp4e/discussions/789
=> Add link to releases to changelog

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java
LSP Specification says "The order of the returned configuration settings correspond to the order of the passed ConfigurationItems (e.g. the first item in the response is the result for the first configuration item in the params). [...] If the client can’t provide a configuration setting for a given scope then null needs to be present in the returned array."
=> Make default implementation of configuration conform to specification

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceDialog.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceHandler.java
=> Fix SWT Resource not properly disposed on LSPSymbolInWorkspaceDialog

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml
0.17.3 due to new format-on-save feature by PR #783
=> Version bumbs

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java
In case where the additionalTextEdits adds longer text then document.length() - offset.
Do not shift offset because of additionalTextEdit until we're done reading interesting bits of this document at the target location (eg indentation information)
=> Fix completion

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/CompleteCompletionTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java
Assuming I have a file with the following content:
```html
<p>
foo<di|
```
(| is the position of the cursor)
and I invoke content assist, which provides a completion `"<div>\n</div>"` with InsertTextMode.AdjustIndentation  .
I would expect the applied completion to look like this:
```html
<p>
foo<div>
</div>|
```
But atm I get this:
```html
<p>
foo<div>
</div>|
```
VSCode on the other hand applies the completion with correct indentation.
This PR fixes the indentation calculation and adds a unit test for it.
=> InsertTextMode.AdjustIndentation when cursor (and completion) is not at the start of the line

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerPlugin.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
so that it can be waited for all these jobs to finish.
=> Set a job family on the update markers from diagnostics job

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/console/DSPProcess.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/console/DSPStreamMonitor.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
* Fix some bugs in case DAP process doesn't exist
* Buffer streams by default so they're not discarded when received before console shows
=> Enable console for vscode-js-debug

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
When dealing with startDebugging request, also terminate debuggees when parent is terminated
=> Terminate debuggees

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPThread.java
Those operations typically work on the list of *known* threads, there is no need to refresh the threads at that time, and in case DAP's threads() request doesn't run well on non-suspended targets, then the former implementation could lead to bogus states.
=> Do not try to refresh threads to compute resume/suspend

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java
Prevent failure of DocumentContentSynchronizer.<init> if the document
does not have an URI registered in EFS and it is not a file uri.
Also improve the existing log to include the URI that we are failing to
deal with.
=> Document content synchronizer

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/CompleteCompletionTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/CompletionSnippetParser.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java
Hello everyone,
we are making extensive use of completions with InsertTextFormat.Snippet and had some problems with completions that try to insert keys with $ in them, because `\$` was inserted as is.
So I tried to improve the parsing of snippets to be closer to the spec (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax) and/or closer to what VSCode does.
Since the snippet format is fairly complex, I extracted the parser into its own class, so I could keep the current parser offset in a field.
This PR fixes
- variables with default values (like `${TM_SELECTED_TEXT:defaultval}`}
- escaping of special characters like dollar, brackets and comma with \ (like `special\$key`)
The following complicated parts of the snippet format are not …
=> Improved parsing of completions with InsertTextFormat.Snippet

target-platforms/target-platform-latest/target-platform-latest.target
Remove Maven Artifacts from the target, as the lastest version of PDE cannot resolve them.
=> Remove Maven Artifacts from the target

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/highlight/HighlightTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/TestUtils.java, org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServer.java, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServerMultiRootFolders.java, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockTextDocumentService.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/highlight/HighlightReconcilingStrategy.java
This commit resolves a bug related to erroneously persisted highlights
in source files. It includes a unit test that verifies the correctness
of the fix, and a few minor improvements to the testing framework.
---
Bug Description: Before this change, source highlights would sometimes
persist after a source view was closed. This would happen, for example,
after the following sequence of steps:
1. Open a source. Ensure that some keyword is highlighted.
2. Activate the option "Toggle Split Editor (Horizontal)".
3. In the newly opened source view, highlight a different keyword.
4. At this point, both sets of highlights (the one from step 1 and the
one from step 3) should be visible in both source views. This is correct
behavior.
5. Close one of the source views, while keeping the other open. …
=> Ensure that active highlights are removed when a source view is closed

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/HasLanguageServerPropertyTester.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyCommandHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/LSPDocumentAbstractHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/references/LSFindReferences.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/rename/LSPRenameHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/selectionRange/LSPSelectionRangeAbstractHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInWorkspaceHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/typeHierarchy/TypeHierarchyHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/typeHierarchy/TypeHierarchyViewHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/EditorToOutlineAdapterFactory.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/UI.java
Fix for #859.
There are multiple occasions in the code where editor parts are casted to ITextEditor. As a result, lsp editors embedded in MultiPage editors don't have the full functionality.
Additionally many handlers use UI::getActiveTextEditor, IMHO getting the editor from ExecutionEvent would be cleaner.
As most handlers (except one) work with ITextEditor, I added a convenience execution method to `LSPDocumentAbstractHandler` for this use case. I refactored the existing handlers to use this method, which was basically removing the casts.
I created a new method UI::asTextEditor as central place for obtaining ITextEditor from an IEditorPart. This method could additionally try to adapt to ITextEditor, which would enable more use cases, but I didn't want to introduce this for this PR.
=> Limited Functionality of LSP Editors in MultiPart Editors #859

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileDialog.java
The quick outline view (in my case used with the C/C++ editor based on LSP) behaved odd. It did not close after selecting an element symbol) in an open file. There was also an x button missing.
I fixed that.
=> Fix closing quick outline dialog after selection

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/CancellationUtil.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java
If the language server throws a `CancellationException` upon cancelling a request, this should not be logged as an error by the `LanguageServerPlugin`.
A check to ensure this behavior already exists in some locations (e.g., `org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(ITextViewer, int)`).
However, other locations where this check should be performed do not include it. This commit introduces the missing checks.
=> Prevent error logging for RequestCancelledExceptions

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/diagnostics/DiagnosticsTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/BlockingWorkspaceJob.java, org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
As requested by @mickaelistria in #885 , here is a pull request that highlights where exists() checks might be missing.
The fix is probably wrong because I wasn't actually able to reproduce the problem. The associated test seems to trigger a different problem.
I suppose the original problem is triggered by the order of operations. I don't know enough to reproduce it in a test case.
=> Add rough sketch for a bugfix for #885

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
Splitting \r\n line endings leads to a BadLocationException while TextViewer.setRedraw is executed during a document.replace operation triggered by a TextEdit.
fixes #902
=> [#902] Do not split line endings in edits

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/LSPSymbolInFileDialog.java
There are a few cases, where updating the selection / cursor position in an open editor might fail. In those cases the solution from PR #901 might not work and the user could only close the quick outline view with the ESC key (the dialog has no x Button). Instead of first updating the editor's selection and then closing the quick outline view, I suggest to change the order, i.e. first close the quick outline view and then update the editor's selection.
=> Fix closing quick outline view

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java
Previously, it was possible for the `viewer` variable used in `LSPDocumentLinkPresentationReconcilingStrategy.underline()` to be nullified externally, which caused a null-pointer exception for the call `viewer.getTextWidget()`.
This commit solves this problem by saving the relevant viewer as a variable local to the
`LSPDocumentLinkPresentationReconcilingStrategy.underline()` function.
=> Fix NPE if ITextViewer is nullified during call to .underline()

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java
This change prevents reconcile run on every dirty region which can be many thousands in a large source file (> 5000 lines) Since the reconciler operate on the whole document it needed to be executed only when the file document changes.
fixes #932
=> [#932] prevent reconcile on every dirty region

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java
The method
ProjectionAnnotationModel.modifyAnnotations(Annotation[], Map<? extends Annotation, ? extends Position>, Annotation[]) does not consider Position changes in any cases. On large annotations the positions won't get updated properly which leads to removed folding annotations.
fixes #934
=> [#934] fix removed folding annotations on document change

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatFilesHandler.java
This commit adds org.eclipse.lsp4e.operations.format to the list of exported packages to enable consumers to implement formatting for objects which do not readily adapt to an IFile. There is also a small refactor of the LSPFormatFilesHandler class with the same goal.
=> Make formatting operations available to consumers

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java
This PR addresses #703 by limiting the maximum number of elements rendered in the UI to 5000 elements.
On my workstation Eclipse can add/render around 1.000 elements per second to the outline. Since adding elements is done in the UI thread, more elements mean longer freeze on initial population and each update.
=> Support limiting the number of outline symbols to avoid UI freezes

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/operations/inlayhint/LSPLineContentCodeMiningTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/LSPLineContentCodeMining.java
`InlayHint` may have a number of `InlayHintLabelPart`s. This is necessary support to determine which label part has been clicked on to execute the command corresponding to the clicked label part.
Includes a test for a single label part
=> Support click on inlayhint label parts

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
Introduces logic to gracefully handle a user-requested cancellation of the initializeFutureMonitor.
=> Handle cancellation of initializeFutureMonitor in LSWrapper

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ServerMessageHandler.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/SupportedFeatures.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/UI.java
`WorkspaceEdit` has a map of change annotations where any change annotation is associated with edits from the workspace edit. If any of change annotations has `needsConfirmation` flag on then VSCode would bring up the refactor preview with annotated changes unchecked.
This PR proposes similar (but not the same, there are limitations) behaviour into Eclipse.
If there is at lease one change annotation that requires confirmation then refactor wizard is opened with the Preview page opened. All changes would be checked marked as I couldn't find how to control this piece. Another limitation is Eclipse text edits are in reverse order (they are applied in reverse order for a reason) but the preview doesn't allow to set the tree sorter on the preview tree.
@rubenporras @mickaelistria …
=> Refactor Preview for WorkspaceEdit with `needsConfirmation` flag

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
If the change is rename and then modify the content of a file. This translates into
1. Delete the file
2. Create the new named file 
3. Set its new content 
This doesn't let to see the diffs in the refactor preview between the old file name file and the new name file side by side. If the Rename or MoveRename ResourceChange is used then refactor preview has more useful content.
This PR suggests to use Rename and MoveRename if this possible, i.e. both resources are in the workspace.
=> Use Rename and MoveRename ResourceChange classes if possible

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
This commit follows up on the discussion started at
https://github.com/eclipse/lsp4e/pull/947#discussion_r1526226952.
It removes the UI-blocking pop-up window that would appear when calling
org.eclipse.lsp4e.LanguageServerWrapper.getInitializedServer()
from a UI thread.
A progress indicator reflecting the status of the server's
initialization will still be displayed in the "Progress" view.
=> Remove UI-blocking pop-up in LSWrapper.getInitializedServer()

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/declaration/OpenDeclarationHyperlinkDetector.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/Messages.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/messages.properties
Instead of collecting only definitions (and type definitions and implementations), I modified the code to also collect declarations for the command "open declaration" in LSP4E. For example, in C++, that makes a difference, since methods can be defined, e.g. in .cpp files and declared in .hpp files.
=> Fix #969 Add collecting of declarations in addition to definitions

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/folding/FoldingTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java
if the imports are collapsed by the editor.
=> Add a preference foldingReconcilingStrategy.collapseImports to control

org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServer.java, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockTextDocumentService.java
Root cause is that `MockLanguageServer#addRemoteProxy` is invoked concurrently which adds the remote proxy to an `ArrayList` which is not thread-safe
=> Fix erratic test failure in DiagnosticsTest#testDiagnosticsFromVariousLS

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/diagnostics/DiagnosticsTest.java
This PR fixes the erratic test failure `FileSystemException: The process cannot access the file because it is being used by another process` seen on Windows in `DiagnosticsTest#testDiagnosticsForMarkerUpdateAfterDeletedFile`:
```py
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
at org.eclipse.core.internal.resources.Resource.delete(Resource.java:816)
at org.eclipse.core.internal.resources.Resource.delete(Resource.java:772)
at org.eclipse.lsp4e.test.diagnostics.DiagnosticsTest.testDiagnosticsForMarkerUpdateAfterDeletedFile(DiagnosticsTest.java:192)
Contains: Could not delete 'D:\junit-workspace\DiagnoticsTest1714763955417\test1714763955426.lspt'.
org.eclipse.core.runtime.CoreException: Could not delete: …
```
=> Fix erratic test failure in DiagnosticsTest

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/LSPLineContentCodeMining.java
Adds a space separator between the inline type hint and the variable name.
Before this PR:
After this PR:
This is similar to what JDT does:
https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/6333016444d089418d28a0e5e331ae3545030d82/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/codemining/JavaMethodParameterCodeMining.java#L31
=> Add spacing to inline type hints. Fixes #981

org.eclipse.lsp4e.test/pom.xml
This PR specifies min/max heap settings to address OOM issue and for more reproducible builds across build environments.
=> specify min/max heap settings for surefire tests

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServersTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/VersioningSupportTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/DocumentDidChangeTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/TestUtils.java
This commit fixes the NPE:
```
org.eclipse.lsp4e.test.LanguageServersTest.testCancellable -- Time
elapsed: 0.112 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke
"org.eclipse.jface.text.ITextViewer.getTextWidget()" because "viewer" is
null
at org.eclipse.lsp4e.test.LanguageServersTest.testCancellable(LanguageServersTest.java:789)
```
which may occur for the code:
```java
IEditorPart editor = TestUtils.openEditor(testFile);
ITextViewer viewer = LSPEclipseUtils.getTextViewer(editor);
IDocument document = viewer.getDocument();
```
where viewer may be null if it has not been initialized fast enough in the UI thread.
As a remedy, a `waitForAndAssertCondition` is added to the function `openTextViewer`:
```java
public static ITextViewer openTextViewer(IFile file) throws …
```
=> Fix erratic NPE in LanguageServersTest#testCancellable

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
When running the test suite on Windows and in Docker with Ubuntu, **a lot** of NPEs with the following stacktrace are thrown:
```py
java.lang.NullPointerException: Cannot invoke
"org.eclipse.core.runtime.IProgressMonitor.done()" because
"this.this$0.initializeFutureMonitor" is null
at org.eclipse.lsp4e.LanguageServerWrapper$2.run(LanguageServerWrapper.java:407)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
and because of the NPE random tests seem to fail.
=> Fix race condition in LanguageServerWrapper resulting in NullPointerException during LS initialization

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/LSPCodeActionMarkerResolution.java
=> Check if the marker still exists before calculating a marker resolution

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSCompletionProposal.java
In addition:
* fix one null warning given by the JDT
* remove `this.` whenever possible to make the code style consistent
=> Fix NPE if there is no completion provider

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/SupportedFeatures.java
=> Register PublishDiagnosticsCapabilities

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/refactoring/LSPTextChange.java
Looks like checking for `null` edit is a proper thing to do as `TextChange` from LTK has an assert `null` for the previous edit. Assertion exception appears in e4.32 but looks like the PR above fixes it.
=> Avoid assertion failure

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/InlayHintProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/LSPLineContentCodeMining.java
According to ICodeMining.getAction(), null should be returned if there is no action to be executed when the mining is clicked.
When several InlayHintLabelParts are used, we cannot be sure if there is an action or not without knowing the actual MouseEvent. However, if no InlayHint has an action, we can be sure there is none even without knowing the MouseEvent. For these cases, the code returns null now.
=> Do not return a Consumer<MouseEvent> if the code mining has no action.

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPThread.java
We have started to experiment with replacing our custom debuggers in the [Eclipse Epsilon](https://eclipse.dev/epsilon/) project with LSP4E-based debuggers, and we've noticed one odd issue when we stop at a breakpoint and then resume and let the program stop. This pull request proposes a workaround for the issue for the time being - the deeper issue seems to be how to handle the case where a `continue` request resumes all threads.
In one of our test programs, we have a main thread T1 start, then another thread T2 starts and stops at a breakpoint. In the Epsilon debug adapter, we stop all threads when we hit a breakpoint, so our `stopped` event provides both the specific thread that hit the breakpoint, and also calls `setAllThreadsStopped(true)`. Our program stops as expected, like this:
I …
=> DSPThread: cannot be suspended if program is terminated

org.eclipse.lsp4e/META-INF/MANIFEST.MF
I'm in the process of getting us off a custom (shaded) version of lsp4e. We use some of the rename classes for a custom rename command initiated via a code lens, but this won't compile with production lsp4e as the package isn't exposed. Any objection to exposing it in the same way as some of the other operations (exposed but marked as private so you get a warning)?
=> lsp4e: Patch so we have access to the rename operations

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java
=> Handle errors coming from LS responses for completion items

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
with transferTo method.
fixes #1045
=> [#1045] replace removed FileUtil.transferStreams

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/console/DSPProcess.java
Fix small logic error when checking if thread is still alive
=> DSPProcess::getExitValue should only raise an exception if the process is still alive

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java
Before this commit, the outline view is drawn with all elements collapsed by default. This often results in plenty of wasted space in the UI and low information density.
Instead, as discussed in #693, it would be preferable to draw the outline view with its first level expanded by default (i.e., displaying the root node and its immediate children by default).
Issue: #693
=> Expand root outline view in outline view by default

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/edit/LSPEclipseUtilsTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java
Trying to open an external file located at the root of a filesystem results in:
```py
java.lang.IllegalArgumentException: Path must include project and resource name: /solarized-dark-color-theme.json
at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2234)
at org.eclipse.core.internal.resources.Container.getFile(Container.java:196)
at org.eclipse.lsp4e.LSPEclipseUtils.getFile(LSPEclipseUtils.java:1229)
at org.eclipse.lsp4e.LSPEclipseUtils.toUri(LSPEclipseUtils.java:371)
at org.eclipse.lsp4e.operations.codelens.CodeLensProvider.provideCodeMinings(CodeLensProvider.java:34)
at org.eclipse.lsp4e.operations.codelens.CodeLensProvider.provideCodeMinings(CodeLensProvider.java:66)
at …
```
=> fix: opening file outside of workspace may throw Exception. Fixes #913

org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/CNFOutlinePage.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/LSSymbolsContentProvider.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/OutlineViewFilterMenuContributor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/OutlineViewHideSymbolKindMenuContributor.java
Add generic implementation of content filtering in the outline view based on an element's SymbolKind and corresponding preferences, which make the user settings persistent.
=> Add content filtering to outline view based on SymbolKind (fix issue #254)

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java
This partially fixes the problem described in #1051
=> Defer creation of dummy process until we actually have something to output (#1051)

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
Add `@Nullable` Annotation to LSW.connect(document, file) to revert to the state before setting `NonNullByDefault` (3ed68da2e2c21ee12364495b5576d609065d26fb)
=> Add @Nullable Annotation to LSW.connect(document, file)

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LaunchConfigurationStreamProvider.java
the current implementation is sub optimal as it creates a new queue element for each byte read from the process.
the new implementation queues arrays of bytes instead resulting in fewer queue elements and in avoiding `byte -> Byte -> byte` conversions. this also reduces GC pressure in the Eclipse IDE process.
I also implemented `read(final byte[] buf, final int off, final int len) ` which also improves bulk read performance.
=> perf: improve StreamProxyInputStream

org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/internal/CharsInputStreamTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/internal/DocumentInputStreamTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentInputStream.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/CharsInputStream.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/DocumentInputStream.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/DocumentUtil.java
This PR replaces the current DocumentInputStream implementation which does not handle high/low surrogate character pairs.
=> fix: DocumentInputStream does not handle surrogate pairs correctly

org.eclipse.lsp4e/src/org/eclipse/lsp4e/IMarkerAttributeComputer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/DiagnosticAnnotation.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java
This PR extends the `IMarkerAttributeComputer` with a method `computeMarkerMessage(Diagnostic)` allowing language server providers to customize the message to be used for markers.
=> feat: make diagnostic marker messages configurable

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/SupportedFeatures.java
This PR cleans up the SupportedFeatures class:
1. Format code for better readability
1. use primitive `true` instead of verbose Boolean.TRUE
1. use `SymbolKind.values()` instead of naming each symbol kind separately
=> refact: cleanup SupportedFeatures class

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/EditorToOutlineAdapterFactory.java
EditorToOutlineAdapterFactory uses IEditorPart as cache key to cache references to slowly starting langservers. when editor parts are closed they are not removed from the hashmap. Using a WeakHashMap solves it.
=> fix: memory leak in EditorToOutlineAdapterFactory

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPLaunchDelegate.java
This commit replaces `Collections.synchronizedList(new LinkedList<Byte>())` with `new ConcurrentLinkedQueue<Byte>()` and only determines the console encoding once and not on every text output. 
If the console encoding was not specified in the launch config it now falls back to the JVM's default encoding instead of throwing an exception.
=> perf: improve DSPLaunchDelegate debug adapter monitor performance

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerPlugin.java
The goal of this PR is to address https://github.com/eclipse/lsp4e/issues/899 , https://github.com/eclipse/lsp4e/issues/536 and https://github.com/eclipse/lsp4e/issues/203 by logging BadLocationExceptions in LSPDiagnosticsToMarkers and SymbolsLabelProvider only when `Platform.getDebugOption("org.eclipse.lsp4e/debug")` is set to true.
=> fix: don't log same BadLocationException excessively

org.eclipse.lsp4e/plugin.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/HasCNFOutlinePage.java
This PR should be merged before merging PR #1075.
=> Fix disappearing sort button in outline view (fix #1091)

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPBreakpointManager.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/debugmodel/DSPDebugTarget.java, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/launcher/DSPLaunchDelegate.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LSJavaCompletionProposalComputer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageClientImpl.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/LSPCodeMining.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/LSContentAssistProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java, target-platforms/target-platform-latest/target-platform-latest.target
This PR bumps no-npe to version 1.1.0 (which contains more refined external null annotation) and applies all necessary code changes to satisfy null analysis checks by the Eclipse compiler.
=> refact: improve null analysis

org.eclipse.lsp4e/src/org/eclipse/lsp4e/DocumentContentSynchronizer.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codelens/LSPCodeMining.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatter.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/inlayhint/LSPLineContentCodeMining.java
`getServerCapabilities()` can block for up to 10 seconds. In code locations where the result is a future anyways it is useful to have a `getServerCapabilitiesAsync()`
I am planning to use `getServerCapabilitiesAsync()` more in future PRs where it will play nicely with the then suggested changes.
Addresses https://github.com/eclipse/lsp4e/issues/628
=> feat: introduce LanguageServerWrapper#getServerCapabilitiesAsync

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/codeactions/CodeActionMarkerResolution.java
Adapt resolveCodeAction to handle timeout and interrupted exception to follow the usual pattern in the codebase (TimeoutException -> log warning giving the time constraint, InterruptedException -> interrupt thread and log error).
=> fix: Adapt resolveCodeAction to handle timeout and interrupted exception

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
Some language servers such as OmniSharp may (erroneously but not fatally) re-register the same capability multiple times. Instead of crashing in such case, just log.
=> Do not crash on re-registration

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServerWrapperTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/AbstractTestWithProject.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/TestUtils.java
This PR temporarily disables the LanguageServerWrapperTest#testStopAndActive test on Windows which currently results in frequent OOMs. Once https://github.com/eclipse/lsp4e/issues/1103 is fixed it should be re-enabled.
This PR also addresses intermittent NPEs and `java.lang.IllegalArgumentException: Attempted to beginRule: P/WorkspaceFoldersTest_testPojectCreate_1726575959224, does not match outer scope rule: P/` when creating projects.
This PR should fix #1109.
=> fix: avoid intermittent test failures

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LSPEclipseUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/LSPTextHover.java, repository/category.xml, target-platforms/target-platform-latest/target-platform-latest.target
commonmark is the library used internally by the JDK and by JDT for markdown rendering. It's more standard and leaner than wikitext.
=> Render markdown with commonmark instead of wikitext

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/symbols/WorkspaceSymbolQuickAccessElement.java
When you have multiple workspace symbols with the same label, only one shows up in the workspace quick access list. The reason is that the filtering and sorting mechanism of the quick access dialog uses a comparator for a set that uses the `getSortLabel` method of the elements - which refers to `getLabel` by default.
This PR overrides the default implementation and makes sure (by adding the random extension ID to make symbols unique) that  `getSortLabel` returns different values for different symbols, even if they have the exact same label.
As a follow-up here, we should think about showing more information for a symbol on the dialog to allow users to distinguish those symbols with the same label somehow, but that is a task for a separate PR or issue.
=> set sort label for quick access elements to avoid symbols get removed when they have the same label

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServerWrapperTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/MockConnectionProviderMultiRootFolders.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
In #1103, it was noted that
LanguageServerWrapperTest#testStopAndActivate causes OOM errors. On investigation, it was discovered that there are multiple causes for this.
1) The MockConnectionProviderMultiRootFolder used in the test created a message processor thread in LSP4J on each call to start() but did not shut them down.
2) The termination of the start/stop loop in the test was wrong: the loop ran for as long as the VM running tests was alive. 3) The "already stopping" logic in LanguageServerWrapper#shutdown was wrong: while the shutdown of a LanguageServerWrapper was processed, further calls to shutdown were ignored.
4) There was a race between the initializationFuture of the LanguageServerWrapper and the future used for shutdown.
With this commit, the test is rewritten to avoid …
=> fix: improve startup and shutdown

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/format/FormatTest.java, org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServer.java, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockTextDocumentService.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/format/LSPFormatter.java
This PR fixes selective formatting.
=> Fix selective formatting (issue #1127)

org.eclipse.lsp4e.tests.mock/META-INF/MANIFEST.MF, org.eclipse.lsp4e.tests.mock/src/org/eclipse/lsp4e/tests/mock/MockLanguageServer.java
By changing the visibility of the MockLanguageServer constructor from private to protected.
=> fix: Allow derived MockLanguageServer for derived servers.

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF, org.eclipse.lsp4e.jdt/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml
The vendor for org.eclipse.lsp4e.debug was missing. Some of the other plugins used Eclipse.org as vendor.
=> Set the vendor of all plugins to Eclipse LSP4E

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java
Semantic highlighting might be applied on top of other highlighting (e.g. diff highlighting in a compare view editor) -> merge instead of replacing
=> fix: merge instead of replacing style from semantic highlighting

org.eclipse.lsp4e/plugin.xml
Ensures that the actions Link with editor, Show Kind, Hide... stay visible if an LSP editor becomes active.
See https://github.com/eclipse-lsp4e/lsp4e/issues/254#issuecomment-2483262272
This PR is related to issue #254.
=> Fix disappearing menu in outline view

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/LSPTextHover.java
=> fix: Do not log InterruptedException as error in LSPTextHover

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/hover/HoverTest.java
The ignored hover has an issue that active part becomes package explorer all of a sudden when hover shell is brought up.
For the test to pass I simply decided to activate the expected editor part manually. After all the test is to verify that intro URL's clicked on the hover are working.
=> Fix failing in Eclipse 4.34 hover test

CHANGELOG.md, CONTRIBUTING.md, README.md, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServerWrapperTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/TokenTypeMapper.java
updates `https://github.com/eclipse/lsp4e` to `https://github.com/eclipse-lsp4e/lsp4e`
=> docs: update repo URLs

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsLabelProvider.java
This caches the repeated findResourceFor(URI) calls in SymbolsLabelProvider.getImage() that can result in performance issues as described in #907
=> perf: add findResourceFor(URI) cache to SymbolsLabelProvider #907

org.eclipse.lsp4e.debug/META-INF/MANIFEST.MF, org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/breakpoints/TextSelectionToIVariable.java
+ Convert sourceElement to URI before comparing paths
+ Bump point version of org.eclipse.lsp4e.debug
=> fix: Path matching in TextSelectionToIVariable does not work on Windows

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/internal/HumanFriendlyComparatorTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/HumanFriendlyComparator.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/OutlineSorter.java
This addresses https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/issues/1616
Currently sorting does not sort numbers numerical.
|before PR|after PR|
|-|-|
|![image](https://github.com/user-attachments/assets/df6bbdb6-4c7d-465d-bd58-18f23f8f8497)|![image](https://github.com/user-attachments/assets/8f42bd9d-a5b4-42cb-8e4a-8b5355e971d4)|
=> fix: use human-friendly sorting in Outline

org.eclipse.lsp4e/plugin.properties, org.eclipse.lsp4e/plugin.xml
I tried to add some new UI contributions to the plugin.xml and was overwhelmed by its organically grown structure. To address this, I reorganized the file to improve readability and maintainability. I grouped configuration elements by feature, such as outline toolbar contributions, code folding, find references support, and others. This makes it easier to follow the purpose of each section and to contribute new features. For example, adding a new outline toolbar button is now straightforward because all the relevant building blocks are grouped together.
I hope you agree that this refactoring improves the file’s clarity and usability. 🤞
---
Since the Git diff is not helpful for showing the structural changes, I wrote a small Python script to compare the effective differences between two …
=> refact: restructure plugin.xml

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/LanguageServersTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServers.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServiceAccessor.java
This PR addresses https://github.com/eclipse-lsp4e/lsp4e/issues/894
`LanguageServers.forProject(...).anyMatching()` may unexpectedly block for up to 10 seconds per matching language server.
The issue occurs because `LanguageServers.forProject(...).anyMatching()` internally calls `LanguageServiceAccessor.capabilitiesComply()`, which in turn invokes `LanguageServerWrapper.getServerCapabilities()`. This method waits up to 10 seconds for the server to initialize, causing potential delays.
This fix ensures non-blocking behavior by addressing the synchronous invocation chain.
---
The offending call chain is:
```py
org.eclipse.jface.text.TextViewerHoverManager.doPresentInformation() or
org.eclipse.ui.internal.views.markers.MarkersTreeViewer.doUpdateItem()
-> …
```
=> fix: Prevent LanguageServers.forProject().anyMatching() from blocking

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java
- Avoid so many calls ProjectionViewer.postCatchupRequest by computing a map from Position to FoldingAnnotation for existing annotations.
- Use that map to determine if a new annotation needs to be created.
- LSPFoldingReconcilingStrategy.updateAnnotations is no longer required/used so delete it.
- Make markInvalidAnnotationsForDeletion private because the signature has changed.
https://github.com/eclipse-lsp4e/lsp4e/issues/1180
=> Improve the performance of LSPFoldingReconcilingStrategy.applyFolding

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/folding/FoldingTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/utils/TestUtils.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/FoldingPreferencePage.java
This PR addresses https://github.com/eclipse-lsp4e/lsp4e/issues/884 by adding a new folding option to automatically fold license headers on initial opening of an editor.
If the first foldable comment of a file a license header is determined using a regex `(?i)(copyright|licensed under|all rights reserved|SPDX-License-Identifier)`
The behaviour is different to Eclipse JDT which has an option to generally fold all header comments:
=> feat: support initial folding of license header

org.eclipse.lsp4e/src/org/eclipse/lsp4e/ui/LanguageServersView.java
This PR adds a context menu item to the Language Servers view to copy the selected cell as text to the clipboard. This is esp. handy for troubleshooting to copy the effective command line or PID of an LS.
=> feat: add "Copy Value" context menu item to LanguageServers view

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/SymbolsModel.java
This PR removes the deprecated-for-removal class DocumentSymbolWithFile which has been replaced by DocumentSymbolWithURI.
The class was deprecated in 2023 and is not referenced in any dependent opensource project on GitHub.
=> refact: remove deprecated DocumentSymbolWithFile class

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/server/ProcessStreamConnectionProvider.java
...to allow onExit operations (e.g. to close streams of piped stderr from process) 
fixes #1194
=> [#1194] make process accessible for subclasses

org.eclipse.lsp4e.debug/src/org/eclipse/lsp4e/debug/presentation/DAPWatchExpression.java
This is a proposed fix for #1199. I add a `null` check to the result of the `adapt` call, as this adaptation may return `null` if you try to edit or re-evaluate the expression after the program has finished running (e.g. between repeated debugging sessions of the same program).
=> DAPWatchExpression: avoid 'Unexpected null value' error when editing expressions

org.eclipse.lsp4e/plugin.xml
=> fix: collapse-all icon not displayed in outline when eclipse jdt plugin is not installed. Fixes #1212

org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/completion/ScoreOfFilterMatchTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/completion/CompletionProposalTools.java
This PR performs a minor refactoring of CompletionProposalTools.getScoreOfFilterMatch()
It also adds a dedicated JUnit test class with test cases to verify functionality of getScoreOfFilterMatch.
The test case `testRandomFilters()` creates several thousands of random filters to proof that the endless loop reported by https://github.com/eclipse-lsp4e/lsp4e/issues/1132 is not caused by `getScoreOfFilterMatch` itself.
=> refact: cleanup of CompletionProposalTools.getScoreOfFilterMatch

org.eclipse.lsp4e.jdt/META-INF/MANIFEST.MF, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LSJavaProposal.java
Rather than just push LS proposals at the top of the proposals list attempt to compute relevance in java editor completion terms. Compute base relevance based on LSP4E proposal category and rank.
=> LS completions relevance in Java editor

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/documentLink/DocumentLinkReconcilingTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java
Before
After
(with quick-reproducer-code mentioned in #1220 )
(I haven't checked LSP4E repository for other possible places where widget's style ranges may be considered to have viewer's document (model) coordinates)
=> Consider viewer's visible region when preparing underline StyleRange[]. Fixes #1220

org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/callhierarchy/CallHierarchyLabelProviderTest.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/callhierarchy/CallHierarchyLabelProvider.java
Fix #1231 and add some test cases.
=> Fix #1231: Add missing separators to call hierarchy item labels

org.eclipse.lsp4e/src/org/eclipse/lsp4e/internal/ResourceForUriCache.java
If a resource is moved or deleted, it's possible that the resource stored for its URI in the ResourceForUriCache stops being `accessible`.
This commit changes `ResourceForUriCache.get(URI)` so that, if a resource is present in the cache but is no longer accessible, the corresponding cache entry is invalidated. In this case, `.get(URI)` then tries to determine the up-to-date IResource again.
Fixes a regression introduced in https://github.com/eclipse-lsp4e/lsp4e/pull/1208. Specifically, this commit
addresses the concern raised in https://github.com/eclipse-lsp4e/lsp4e/pull/1208#discussion_r1942357586
=> fix: automatically invalidate moved/deleted entries from the ResourceForUriCache

org.eclipse.lsp4e.jdt/META-INF/MANIFEST.MF, org.eclipse.lsp4e.jdt/plugin.properties, org.eclipse.lsp4e.jdt/plugin.xml, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/JavaSemanticTokensProcessor.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LSJavaSemanticTokensProvider.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LanguageServerJdtPlugin.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/preferences/LspJdtPreferencesPage.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/preferences/LspJdtPrefsInitializer.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/preferences/PreferenceConstants.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/semanticTokens/SemanticTokensDataStreamProcessorTest.java, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/semanticTokens/SemanticTokensLegendProviderTest.java, org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/AbstractcSemanticTokensDataStreamProcessor.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticHighlightReconcilerStrategy.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticTokensClient.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/semanticTokens/SemanticTokensDataStreamProcessor.java
Based on the latest addition of semantic tokens extension for Java editor the support is added for having semantic tokens from the language server in the Java editor.
There is a preference add to turn off semantic tokens support in the Java editor. The preference is defined but the UI is not and is expected to come from 3rd party plugins using this functionality (i.e. spring boot ls plugin) otherwise it's unclear where to fit this preference in the UI at the moment
=> Semantic tokens from LS available in the Java editor

org.eclipse.lsp4e/src/org/eclipse/lsp4e/outline/CNFOutlinePage.java
Addresses the following sporadic exception seen in the log.
```py
org.eclipse.swt.SWTException: Widget is disposed
at org.eclipse.swt.SWT.error(SWT.java:4932)
at org.eclipse.swt.SWT.error(SWT.java:4847)
at org.eclipse.swt.SWT.error(SWT.java:4818)
at org.eclipse.swt.widgets.Widget.error(Widget.java:501)
at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:420)
at org.eclipse.swt.widgets.Tree.getItems(Tree.java:3389)
at org.eclipse.jface.viewers.TreeViewer.getChildren(TreeViewer.java:165)
at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:839)
at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:818)
at …
```
=> fix: "SWTException: Widget is disposed" in CNFOutlinePage#refreshTreeSelection

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
Ensure getServerCapabilitiesAsync() fails gracefully when serverCapabilities is unexpectedly null.
---
Disclaimer: I haven't seen the reported issue myself, but I’ve improved `getServerCapabilitiesAsync()` anyways to handle a potential null value more gracefully. Additionally, I’ve marked `serverCapabilities` as volatile to address possible visibility issues that could lead also to unexpected NPEs.
=> fix: exception in Outline view when LS fails to start (#1239)

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/FocusableBrowserInformationControl.java
Ensure all JavaScript evaluations in `FocusableBrowserInformationControl` only occur after `document.readyState === 'complete'` to prevent runtime errors when accessing incomplete DOM elements, such as:
```py
org.eclipse.swt.SWTException: Cannot read properties of null (reading 'scrollWidth')
at org.eclipse.swt.browser.Edge.evaluate(Edge.java:908)
at org.eclipse.swt.browser.WebBrowser.evaluate(WebBrowser.java:405)
at org.eclipse.swt.browser.Browser.evaluate(Browser.java:665)
at org.eclipse.swt.browser.Browser.evaluate(Browser.java:614)
at org.eclipse.lsp4e.operations.hover.FocusableBrowserInformationControl.safeEvaluate(FocusableBrowserInformationControl.java:128)
at org.eclipse.lsp4e.operations.hover.FocusableBrowserInformationControl.lambda$0(FocusableBrowserInformationControl.java:95) …
```
=> fix: defer browser evaluations until DOM is ready in hover control

org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LSJavaCompletionWrappingCompletionProposal.java, org.eclipse.lsp4e.jdt/src/org/eclipse/lsp4e/jdt/LspJavaQuickAssistProcessor.java
JDT completions changes 1443a66b9c53cb6f91e5fc0f7805ec5e73f070ea broke CodeAction for JDT coming from LS. This change should restore the behaviour for CodeActions.
=> JDT completions compatible with any `ICompletionProposal`

org.eclipse.lsp4e.jdt/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/META-INF/MANIFEST.MF, org.eclipse.lsp4e.test/pom.xml, org.eclipse.lsp4e.test/src/org/eclipse/lsp4e/test/linkedediting/LinkedEditingTest.java, org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/linkedediting/LSPLinkedEditingReconcilingStrategy.java
Fixes eclipse-wildwebdeveloper/wildwebdeveloper#1844
When selecting a range of characters spanning different linked editing ranges with the keyboard, it resets the selection moving the cursor to the end of the selection.
This PR fixes that issue by skipping that processing of linked editing ranges when the size of the selection changes as these don't seem to be necessary for the linked editing feature.
I don't know whether this is the best way of solving this issue (for example, it might be possible to somehow change the linked editing logic to not modify the selection and then reset it or to explicitly restore the cursor/caret position) but I wanted to at least show one way of doing it.
Alternatively, [applyLinkedEditing](https://github.com/eclipse-lsp4e/lsp4e/blob/0480a5b13ba86af99477812 …
=> skip linked editing update on selection (size) changes

org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerPlugin.java, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java
A document may be modified concurrently by multiple threads. This can cause `BadLocationException`s, which should not be logged unless the log trace is enabled for the LanguageServerPlugin.
Follows a similar pattern to:
https://github.com/eclipse-tm4e/tm4e/pull/888
=> fix: catch expected BadLocationException in LSPFoldingReconcilingStrategy

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java
Currently when a change is made in an `ExtensionBasedTextEditor` that uses document links, the links disappear. This is caused by the region-based `reconcile` method here intentionally doing nothing:
https://github.com/eclipse-lsp4e/lsp4e/blob/cc3fb63d9925b9acb57f299dd9511640d6482b8d/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/documentLink/LSPDocumentLinkPresentationReconcilingStrategy.java#L181-L184
This change adds support for editors that call this `reconcile` method on change.
See Issue #1305 for more details and example gifs showing the problem.
=> Call underline() for region-based reconcile also

org.eclipse.lsp4e/META-INF/MANIFEST.MF, org.eclipse.lsp4e/pom.xml, org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java
removes the Java exception text from displayed error dialog.
fixes #1328
=> [#1328] improve error message on LS start failures

org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/FocusableBrowserInformationControl.java
Javac mentions `int cannot be cast to Double`, so we explicit the double type of the constant.
=> Let code compile with Javac
